import { createHash, randomUUID } from "node:crypto";import { NextResponse } from "next/server";
import { analyzeProductImages, generateProductCopy, researchProduct } from "../../../../../../../lib/commerce/ai";
import { addCaptureFile, getCapture, getCaptureFiles, listPriceRules, updateCapture } from "../../../../../../../lib/commerce/db";
import { createCommerceWebp } from "../../../../../../../lib/commerce/images";import { calculatePrice, DEFAULT_PRICE_RULES, selectPriceRule } from "../../../../../../../lib/commerce/pricing";
export const runtime="nodejs";export const maxDuration=300;
export async function POST(_:Request,{params}:{params:Promise<{id:string}>}){const {id}=await params;const capture=await getCapture(id);if(!capture)return NextResponse.json({error:"Captura no encontrada."},{status:404});
 try{await updateCapture(id,{status:"analyzing",errorMessage:null});const files=await getCaptureFiles(id);const originals=files.filter(f=>f.mime_type.startsWith("image/")&&!f.filename.endsWith(".webp"));const analyzed=await analyzeProductImages(originals.map(f=>({id:f.id,mimeType:f.mime_type,bytes:f.bytes})));await updateCapture(id,{analysis:analyzed.analysis,status:analyzed.analysis.missingCritical.length?"needs_evidence":"researching"});
  const researched=await researchProduct(analyzed.analysis);const generated=await generateProductCopy(analyzed.analysis,researched.research);const source=originals[0];if(source){const webp=await createCommerceWebp(source.bytes);await addCaptureFile(id,{id:`webp_${randomUUID()}`,filename:`${generated.copy.slug||id}.webp`,mimeType:"image/webp",sha256:createHash("sha256").update(webp).digest("hex"),bytes:webp});}
  let priceCalculation;const cost=analyzed.analysis.observedPrice.value;if(typeof cost==="number"&&cost>0){const stored=await listPriceRules(capture.commerce_id);const rules=stored.length?stored:DEFAULT_PRICE_RULES;const rule=selectPriceRule(rules,{commerceId:capture.commerce_id,productId:id,categoryId:analyzed.analysis.category.value??undefined,cost});if(rule)priceCalculation=calculatePrice(cost,analyzed.analysis.observedPrice.currency||"USD",rule);}
  const status=analyzed.analysis.missingCritical.length||!priceCalculation?"needs_evidence":"awaiting_review";await updateCapture(id,{status,research:researched.research,productCopy:generated.copy,priceCalculation});return NextResponse.json({capture:await getCapture(id),usage:{vision:analyzed.usage,research:researched.usage,copy:generated.usage}});
 }catch(error){const message=error instanceof Error?error.message:"Product processing failed";await updateCapture(id,{status:"failed",errorMessage:message});return NextResponse.json({error:message},{status:502});}}
