"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import "../impulsa.css";
import "../impulsa-enhancements.css";

type View="start"|"verify"|"login"|"register"|"code"|"forgot"|"forgotVerify"|"reset";
const showcase=["/catalog/pilot/05-ventilador-gwell-gf-8816.webp","/catalog/pilot/01-tv-philco-ph43hdce.webp","/catalog/gestora/02-cocina-royal-reg202v-ecommerce.webp","/catalog/gestora/03-colchon-konfort-135x190-ecommerce.webp"];

export default function Login(){
 const[view,setView]=useState<View>("start"),[form,setForm]=useState({email:"",password:"",publicName:"",whatsapp:"",accessKey:""}),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[showPassword,setShowPassword]=useState(false),[confirmPassword,setConfirmPassword]=useState(""),router=useRouter();
 const set=(name:string,value:string)=>setForm(x=>({...x,[name]:value}));
 function change(next:View){setView(next);setError("");setNotice("")}
 function start(e:FormEvent){e.preventDefault();setError("");if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)){setError("Escribe un correo válido.");return}change("register")}
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");setNotice("");try{
  if(view==="forgotVerify"){const r=await fetch("/api/gestoras/auth/email/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code:form.accessKey})}),d=await r.json();if(!r.ok)throw new Error(d.error||"No pudimos verificar el código.");change("reset");return}
  if(view==="reset"){if(form.password!==confirmPassword)throw new Error("Las contraseñas no coinciden.");const r=await fetch("/api/gestoras/auth/reset",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password:form.password})}),d=await r.json();if(!r.ok)throw new Error(d.error||"No pudimos cambiar la contraseña.");setNotice("Contraseña actualizada. Ya puedes entrar.");change("login");return}
  if(view==="verify"){const r=await fetch("/api/gestoras/auth/email/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code:form.accessKey})}),d=await r.json();if(!r.ok)throw new Error(d.error||"No pudimos verificar el código.");change("register");return}
  if(view==="forgot"){const r=await fetch("/api/gestoras/auth/recovery",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:form.email})}),d=await r.json();if(!r.ok)throw new Error(d.error||"No pudimos enviar las instrucciones.");setNotice(d.message||"Si existe una cuenta, recibirás instrucciones por correo.");change("forgotVerify");return}
  const endpoint=view==="register"?"/api/gestoras/auth/register":"/api/gestoras/auth/login",body=view==="code"?{accessKey:form.accessKey}:view==="register"?form:{email:form.email,password:form.password},r=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error||"Revisa los datos e inténtalo otra vez.");router.replace("/impulsa");router.refresh()
 }catch(e){setError(e instanceof Error?e.message:"No pudimos continuar.")}finally{setBusy(false)}}
 const title=view==="register"?"Crea tu oficina.":view==="verify"?"Revisa tu correo.":view==="code"?"Acceso autorizado.":view==="forgot"?"Recupera tu acceso.":view==="forgotVerify"?"Revisa tu correo.":view==="reset"?"Crea una contraseña nueva.":"Bienvenida de nuevo.";
 return <main className="impulsa-login premium-auth">
  <section className="auth-showcase" aria-label="Productos y oportunidades NEXO"><div className="showcase-grid">{showcase.map((src,i)=><div key={src}><img src={src} alt=""/><span>{["Energía","Tecnología","Hogar","Descanso"][i]}</span></div>)}</div><img className="showcase-logo" src="/brand/nexo-logo-001g.png" alt="NEXO"/></section>
  {view==="start"?<section className="auth-onboarding"><article className="auth-promise"><span>NEXO IMPULSA</span><h1>Empieza tu negocio con NEXO</h1><p>Crea gratis tu propia oficina, selecciona productos y comparte tu tienda. Gana por cada venta sin comprar inventario.</p></article><form className="auth-start" onSubmit={start}><h2>Empieza gratis</h2><label><span>Correo electrónico</span><div><input type="email" value={form.email} onChange={e=>set("email",e.target.value)} placeholder="Introduce tu correo electrónico" autoComplete="email" required/><button aria-label="Continuar" disabled={busy}>{busy?"…":"→"}</button></div></label>{error&&<div role="alert">{error}</div>}<p>Usaremos este correo para crear y proteger tu acceso.</p><button className="auth-existing" type="button" onClick={()=>change("login")}>Ya tengo una cuenta</button></form></section>:
  <section className="auth-panel"><button className="auth-back" type="button" onClick={()=>change("start")}>← Volver</button><form onSubmit={submit} noValidate><img className="login-logo" src="/brand/nexo-logo-001g.png" alt="NEXO"/><span>IMPULSA</span><h1>{title}</h1><p>{view==="register"?"Completa tus datos para abrir tu tienda NEXO.":view==="verify"?`Enviamos un código de 6 dígitos a ${form.email.replace(/(^.).*(@.*$)/,"$1••••$2")}.`:view==="code"?"Introduce el código privado facilitado por NEXO.":view==="forgot"?"Introduce el correo asociado a tu oficina NEXO.":view==="forgotVerify"?`Enviamos un código a ${form.email.replace(/(^.).*(@.*$)/,"$1••••$2")}.`:view==="reset"?"Usa al menos 10 caracteres y evita reutilizar contraseñas.":"Administra productos, margen, pedidos y ganancias."}</p>
   {view==="register"&&<><label>Nombre de tu tienda<input value={form.publicName} onChange={e=>set("publicName",e.target.value)} autoComplete="organization" required/></label><label>WhatsApp<input value={form.whatsapp} onChange={e=>set("whatsapp",e.target.value)} inputMode="tel" autoComplete="tel" required/></label></>}
   {!["code","verify","forgotVerify","reset"].includes(view)&&<label>Correo<input value={form.email} onChange={e=>set("email",e.target.value)} type="email" autoComplete="email" required/></label>}
   {(view==="login"||view==="register"||view==="reset")&&<label>{view==="reset"?"Nueva contraseña":"Contraseña"}<div className="password-row"><input value={form.password} onChange={e=>set("password",e.target.value)} type={showPassword?"text":"password"} minLength={view==="register"?10:8} autoComplete={view==="register"?"new-password":"current-password"} required/><button type="button" onClick={()=>setShowPassword(x=>!x)}>{showPassword?"Ocultar":"Ver"}</button></div></label>}
   {view==="login"&&<button className="forgot-link" type="button" onClick={()=>change("forgot")}>¿Olvidaste tu contraseña?</button>}
   {view==="reset"&&<label>Confirma la contraseña<input value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} type={showPassword?"text":"password"} minLength={10} autoComplete="new-password" required/></label>}
   {(view==="verify"||view==="forgotVerify")&&<label>Código de verificación<input value={form.accessKey} onChange={e=>set("accessKey",e.target.value.replace(/\D/g,"").slice(0,6))} inputMode="numeric" autoComplete="one-time-code" required/></label>}
   {view==="code"&&<label>Código de acceso<input value={form.accessKey} onChange={e=>set("accessKey",e.target.value)} type="password" autoComplete="one-time-code" required/></label>}
   {error&&<div role="alert">{error}</div>}{notice&&<div className="auth-notice" role="status">{notice}</div>}<button className="auth-submit" disabled={busy}>{busy?"Procesando…":view==="register"?"Crear mi oficina":view==="forgot"?"Enviar instrucciones":view==="verify"||view==="forgotVerify"?"Verificar y continuar":view==="reset"?"Guardar contraseña":"Entrar"}</button>
   {(view==="verify"||view==="forgotVerify")&&<button className="forgot-link" type="button" onClick={start}>Reenviar código</button>}<div className="auth-switch">{view!=="login"&&<button type="button" onClick={()=>change("login")}>Ya tengo cuenta</button>}{view!=="register"&&view!=="verify"&&<button type="button" onClick={()=>change("start")}>Crear mi oficina</button>}{view==="login"&&<button type="button" onClick={()=>change("code")}>Acceso del equipo</button>}</div><a className="help" href="https://wa.me/5354056173" target="_blank" rel="noreferrer">Ayuda por WhatsApp</a>
  </form></section>}
 </main>
}