"use client";
import {useState} from "react";

async function post(body:Record<string,unknown>){const r=await fetch("/api/admin/control",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||"No se pudo guardar");return d;}
export function GestoraStatusAction({gestoraId,status}:{gestoraId:string;status:string}){const[busy,setBusy]=useState(false),[msg,setMsg]=useState("");async function run(next:"active"|"suspended"){setBusy(true);setMsg("");try{await post({action:"gestora_status",gestoraId,status:next});setMsg(next==="active"?"Activada":"Suspendida");location.reload();}catch(e){setMsg(e instanceof Error?e.message:"Error");}finally{setBusy(false)}}return <div className="admin-order-actions"><button disabled={busy||status==="active"} onClick={()=>run("active")}>Activar</button><button className="secondary" disabled={busy||status==="suspended"} onClick={()=>run("suspended")}>Suspender</button>{msg&&<span className="admin-action-note">{msg}</span>}</div>}
export function CampaignActions({id,status}:{id:string;status:string}){const[busy,setBusy]=useState(false);async function set(next:"active"|"paused"){setBusy(true);try{await post({action:"campaign_status",id,status:next});location.reload();}finally{setBusy(false)}}return <div className="admin-order-actions"><button disabled={busy||status==="active"} onClick={()=>set("active")}>Activar</button><button className="secondary" disabled={busy||status==="paused"} onClick={()=>set("paused")}>Pausar</button></div>}
export function CampaignCreate(){const[busy,setBusy]=useState(false),[msg,setMsg]=useState("");return <form className="admin-product-search" onSubmit={async e=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{await post({action:"campaign_create",title:f.get("title"),subtitle:f.get("subtitle"),ctaLabel:f.get("ctaLabel"),ctaUrl:f.get("ctaUrl")});e.currentTarget.reset();location.reload();}catch(err){setMsg(err instanceof Error?err.message:"Error");}finally{setBusy(false)}}}><input name="title" placeholder="Título de campaña" required/><input name="subtitle" placeholder="Texto breve"/><input name="ctaLabel" placeholder="Botón"/><input name="ctaUrl" placeholder="/productos"/><button disabled={busy}>Crear</button>{msg&&<span>{msg}</span>}</form>}
export function SettingForm({settingKey,label,value}:{settingKey:string;label:string;value:string}){const[busy,setBusy]=useState(false),[msg,setMsg]=useState("");return <form className="admin-product-search" onSubmit={async e=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{await post({action:"setting",key:settingKey,value:f.get("value")});setMsg("Guardado");}catch(err){setMsg(err instanceof Error?err.message:"Error");}finally{setBusy(false)}}}><label style={{display:"grid",gap:6,fontWeight:800}}>{label}<input name="value" defaultValue={value}/></label><button disabled={busy}>Guardar</button>{msg&&<span>{msg}</span>}</form>}
export function ResolveIncident({id}:{id:string}){const[busy,setBusy]=useState(false);return <button className="admin-product-status" disabled={busy} onClick={async()=>{setBusy(true);try{await post({action:"incident_resolve",id});location.reload();}finally{setBusy(false)}}}>Marcar resuelta</button>}
export function RequestPayout({gestoraId,currency="USD"}:{gestoraId:string;currency?:string}){const[busy,setBusy]=useState(false),[msg,setMsg]=useState("");return <div><button className="admin-product-status" disabled={busy} onClick={async()=>{setBusy(true);setMsg("");try{await post({action:"payout_request",gestoraId,currency});location.reload();}catch(e){setMsg(e instanceof Error?e.message:"Error");}finally{setBusy(false)}}}>Crear payout</button>{msg&&<small>{msg}</small>}</div>}
export function PayPayout({payoutId}:{payoutId:string}){const[busy,setBusy]=useState(false),[msg,setMsg]=useState("");return <form className="admin-product-search" onSubmit={async e=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{await post({action:"payout_pay",payoutId,method:f.get("method"),reference:f.get("reference"),evidenceUrl:f.get("evidenceUrl")});location.reload();}catch(err){setMsg(err instanceof Error?err.message:"Error");}finally{setBusy(false)}}}><input name="method" placeholder="Método" required/><input name="reference" placeholder="Referencia" required/><input name="evidenceUrl" placeholder="Evidencia (opcional)"/><button disabled={busy}>Marcar pagado</button>{msg&&<span>{msg}</span>}</form>}
