import type { ProductAnalysis, ProductCopy, ProductResearch } from "./types";

const analysisSchema = {
  type:"object", additionalProperties:false,
  required:["targetDescription","brand","model","productType","category","observedPrice","warranty","barcode","qrValue","specifications","includedItems","contradictions","missingCritical","requestedEvidence"],
  properties:{
    targetDescription:{type:"string"},
    brand:fieldSchema(),model:fieldSchema(),productType:fieldSchema(),category:fieldSchema(),warranty:fieldSchema(),barcode:fieldSchema(),qrValue:fieldSchema(),
    observedPrice:{type:"object",additionalProperties:false,required:["value","confidence","origin","imageIds","observedText","currency"],properties:{value:{type:["number","null"]},confidence:{type:"number",minimum:0,maximum:1},origin:{type:"string",enum:["photo","ocr","manufacturer","manual","retailer","inference"]},imageIds:{type:"array",items:{type:"string"}},observedText:{type:["string","null"]},currency:{type:["string","null"]}}},
    specifications:{type:"array",items:{type:"object",additionalProperties:false,required:["name","value","confidence","origin","imageIds"],properties:{name:{type:"string"},value:{type:"string"},confidence:{type:"number",minimum:0,maximum:1},origin:{type:"string",enum:["photo","ocr","manufacturer","manual","retailer","inference"]},imageIds:{type:"array",items:{type:"string"}}}}},
    includedItems:{type:"array",items:{type:"object",additionalProperties:false,required:["value","confidence","imageIds"],properties:{value:{type:"string"},confidence:{type:"number",minimum:0,maximum:1},imageIds:{type:"array",items:{type:"string"}}}}},
    contradictions:{type:"array",items:{type:"string"}},missingCritical:{type:"array",items:{type:"string"}},requestedEvidence:{type:"array",items:{type:"string"}}
  }
};
function fieldSchema(){return {type:"object",additionalProperties:false,required:["value","confidence","origin","imageIds","observedText"],properties:{value:{type:["string","null"]},confidence:{type:"number",minimum:0,maximum:1},origin:{type:"string",enum:["photo","ocr","manufacturer","manual","retailer","inference"]},imageIds:{type:"array",items:{type:"string"}},observedText:{type:["string","null"]}}};}
function outputText(payload:any){for(const item of payload?.output??[])for(const c of item?.content??[])if(c?.type==="output_text"&&typeof c.text==="string")return c.text;return null;}

export async function analyzeProductImages(files:Array<{id:string;mimeType:string;bytes:Buffer}>):Promise<{analysis:ProductAnalysis;usage:any}> {
  const apiKey=process.env.OPENAI_API_KEY;if(!apiKey)throw new Error("OPENAI_API_KEY is not configured");
  const content:any[]=[{type:"input_text",text:`Analiza TODAS las imágenes como un único expediente de producto. Primero identifica cuál es el producto objetivo repetido o protagonista y no confundas productos del fondo. Ejecuta lectura visual/OCR de marca, modelo, precio, moneda, garantía, placa, caja, QR y código de barras. Cada campo debe indicar los imageIds que lo respaldan y una confianza calibrada: 0 si no hay evidencia, <=0.5 si es inferencia, >=0.8 solo si el texto u objeto es legible y consistente. No busques en internet en este paso. No selecciones un producto existente. Si falta una prueba crítica, describe exactamente la próxima foto necesaria. Los imageIds disponibles son: ${files.map(f=>f.id).join(", ")}.`}];
  for(const file of files)content.push({type:"input_image",image_url:`data:${file.mimeType};base64,${file.bytes.toString("base64")}`,detail:"high"});
  const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.NEXO_PRODUCT_VISION_MODEL||"gpt-5.4-mini",store:false,instructions:"Eres el analista visual de NEXO Product Studio. Extraes evidencia, no inventas datos y respondes en español.",input:[{role:"user",content}],text:{format:{type:"json_schema",name:"nexo_product_analysis",strict:true,schema:analysisSchema}}}),signal:AbortSignal.timeout(120_000)});
  if(!response.ok)throw new Error(`OpenAI vision failed (${response.status})`);const payload=await response.json();const text=outputText(payload);if(!text)throw new Error("OpenAI vision returned no structured output");return {analysis:JSON.parse(text),usage:payload.usage??null};
}

export async function researchProduct(analysis:ProductAnalysis):Promise<{research:ProductResearch;usage:any}> {
  const apiKey=process.env.OPENAI_API_KEY;if(!apiKey)throw new Error("OPENAI_API_KEY is not configured");
  if(!analysis.brand.value||!analysis.model.value)return {research:{status:"not_run",summary:"No se investigó porque marca y modelo no están suficientemente identificados.",confirmedFacts:[],contradictions:[],sources:[]},usage:null};
  const query=`Investiga el producto exacto ${analysis.brand.value} ${analysis.model.value}. Prioriza fabricante, manual o ficha técnica oficial; después distribuidores confiables. Contrasta únicamente con esta evidencia fotográfica: ${JSON.stringify({productType:analysis.productType.value,specifications:analysis.specifications.map(x=>[x.name,x.value]),includedItems:analysis.includedItems.map(x=>x.value)})}. Devuelve JSON válido con status (confirmed|partial|not_conclusive), summary, confirmedFacts [{name,value,sourceUrls}], contradictions y sources [{url,title,sourceType,supports,consultedAt}]. No incluyas una URL que no hayas consultado. No copies textos comerciales.`;
  const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.NEXO_PRODUCT_RESEARCH_MODEL||"gpt-5.4-mini",store:false,tools:[{type:"web_search"}],input:query}),signal:AbortSignal.timeout(120_000)});
  if(!response.ok)throw new Error(`OpenAI research failed (${response.status})`);const payload=await response.json();const text=outputText(payload);if(!text)throw new Error("Research returned no output");const match=text.match(/\{[\s\S]*\}/);if(!match)throw new Error("Research output was not JSON");return {research:JSON.parse(match[0]),usage:payload.usage??null};
}

export async function generateProductCopy(analysis:ProductAnalysis,research:ProductResearch):Promise<{copy:ProductCopy;usage:any}> {
  const apiKey=process.env.OPENAI_API_KEY;if(!apiKey)throw new Error("OPENAI_API_KEY is not configured");
  const schema={type:"object",additionalProperties:false,required:["title","seoTitle","slug","sku","shortDescription","description","benefits","specifications","includedItems","warranty","faq","metaDescription","primaryKeyword","relatedKeywords","altText"],properties:{title:{type:"string"},seoTitle:{type:"string"},slug:{type:"string"},sku:{type:"string"},shortDescription:{type:"string"},description:{type:"string"},benefits:{type:"array",items:{type:"string"}},specifications:{type:"array",items:{type:"object",additionalProperties:false,required:["name","value"],properties:{name:{type:"string"},value:{type:"string"}}}},includedItems:{type:"array",items:{type:"string"}},warranty:{type:["string","null"]},faq:{type:"array",items:{type:"object",additionalProperties:false,required:["question","answer"],properties:{question:{type:"string"},answer:{type:"string"}}}},metaDescription:{type:"string"},primaryKeyword:{type:"string"},relatedKeywords:{type:"array",items:{type:"string"}},altText:{type:"string"}}};
  const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.NEXO_PRODUCT_COPY_MODEL||"gpt-5.4-mini",store:false,instructions:"Redacta contenido original de ecommerce en español para NEXO. Usa solo hechos respaldados; convierte incertidumbre en advertencia, nunca en promesa.",input:JSON.stringify({analysis,research,availabilityWarning:"Producto sujeto a confirmación de disponibilidad. NEXO verifica existencia y precio antes de completar la compra."}),text:{format:{type:"json_schema",name:"nexo_product_copy",strict:true,schema}}}),signal:AbortSignal.timeout(90_000)});
  if(!response.ok)throw new Error(`OpenAI copy failed (${response.status})`);const payload=await response.json();const text=outputText(payload);if(!text)throw new Error("Copy generation returned no output");return {copy:JSON.parse(text),usage:payload.usage??null};
}
