import type { ProductKnowledgeSeed } from "./knowledge";

export const productBatchKnowledgeSeeds20260902: ProductKnowledgeSeed[] = [
  {
    id:"pk_ecoflow_delta3_classic",woocommerceProductId:1133,sku:"NEXO-ECOFLOW-DELTA3-CLASSIC",brand:"EcoFlow",model:"DELTA 3 Classic",aliases:["EcoFlow Delta 3 Classic","Delta 3 1024Wh","estación EcoFlow 1800W"],productType:"Estación de energía portátil",confidence:"confirmed_external",
    summary:"Estación portátil LiFePO₄ de 1.024 Wh, salida AC nominal de 1.800 W, sobretensión de 3.600 W, entrada solar de hasta 500 W y control mediante la aplicación EcoFlow.",
    customerDescription:"Respaldo eléctrico portátil para apagones, trabajo y actividades fuera de la red. Puede alimentar varios equipos dentro de sus límites y recargarse por corriente, panel solar, vehículo o generador compatible.",
    specs:[
      {name:"Capacidad",value:"1024",unit:"Wh",confidence:"confirmed_external",evidence:"EcoFlow DELTA 3 Series oficial"},{name:"Química",value:"LiFePO₄",confidence:"confirmed_external",evidence:"EcoFlow oficial"},{name:"Salida AC nominal",value:"1800",unit:"W",confidence:"confirmed_external",evidence:"EcoFlow oficial"},{name:"Sobretensión",value:"3600",unit:"W",confidence:"confirmed_external",evidence:"EcoFlow oficial"},{name:"X-Boost",value:"hasta 2600 W para determinadas cargas resistivas",confidence:"confirmed_external",evidence:"EcoFlow oficial; no equivale a sobretensión"},{name:"Entrada solar",value:"hasta 500",unit:"W",confidence:"confirmed_external",evidence:"EcoFlow oficial"},{name:"Carga AC 0–80 %",value:"aprox. 45 minutos",confidence:"confirmed_external",evidence:"EcoFlow oficial, condiciones del fabricante"},{name:"Vida útil anunciada",value:"más de 3000 ciclos hasta 80 %",confidence:"confirmed_external",evidence:"EcoFlow oficial"},{name:"Control",value:"aplicación EcoFlow por Wi‑Fi/Bluetooth",confidence:"confirmed_external",evidence:"EcoFlow oficial"},{name:"Garantía NEXO",value:"5 días por fallos del equipo",confidence:"confirmed_nexo",evidence:"Condición comercial suministrada por NEXO"}],
    faq:[{question:"¿Puede alimentar un refrigerador?",answer:"Puede hacerlo si el consumo continuo y el pico de arranque del refrigerador permanecen dentro de los límites de la estación. NEXO debe revisar la etiqueta del equipo antes de prometer autonomía.",audience:"customer",confidence:"confirmed_external"},{question:"¿Cuántas horas dura?",answer:"Depende del consumo. Como cálculo orientativo: horas ≈ 1.024 Wh × eficiencia útil ÷ watts de la carga; el resultado real cambia por temperatura, estado de batería y picos.",audience:"gestora",confidence:"confirmed_external"},{question:"¿Incluye panel solar?",answer:"No está confirmado. La estación admite entrada solar, pero el panel se considera separado salvo que el anuncio indique expresamente lo contrario.",audience:"customer",confidence:"unknown"}],
    sources:[{sourceType:"physical_photo",title:"Foto suministrada de EcoFlow DELTA 3 Classic",supports:["identidad visual","formato","panel frontal"],confidence:"confirmed_nexo"},{sourceType:"manufacturer",title:"EcoFlow DELTA 3 Series",url:"https://eu.ecoflow.com/products/delta-3-series-portable-power-station",supports:["capacidad","potencia","batería","recarga","entrada solar","aplicación"],confidence:"confirmed_external"}],
    salesPlaybook:{benefits:["Respaldo durante apagones","Recarga rápida","Batería LiFePO₄ duradera","Entrada solar y control por app"],idealCustomer:["Hogares con cortes eléctricos","Profesionales que necesitan energía móvil","Usuarios con equipos esenciales compatibles"],sellingPoints:["1.024 Wh y 1.800 W en formato portátil","0–80 % en aproximadamente 45 minutos"],objections:[{objection:"¿Me dura toda la noche?",answer:"Solo puede estimarse con el consumo real de los equipos conectados; solicita fotos de sus etiquetas.",confidence:"confirmed_external"}],warnings:["No confundir X-Boost con potencia de sobretensión.","No prometer autonomía sin conocer watts y pico de arranque."]},gaps:[{question:"¿Qué cables y accesorios incluye exactamente esta unidad?",requiredEvidence:"Foto del contenido de la caja",priority:"medium"}]
  },
  {
    id:"pk_epson_et2400",woocommerceProductId:1135,sku:"NEXO-EPSON-ET2400",brand:"Epson",model:"EcoTank ET-2400",aliases:["Epson ET-2400","EcoTank 2400","impresora Epson sin cartuchos"],productType:"Impresora multifunción de tanque",confidence:"confirmed_external",
    summary:"Multifunción EcoTank para imprimir, escanear y copiar, con tanque recargable, Wi‑Fi/Wi‑Fi Direct, USB, bandeja de 100 hojas y control desde Epson Smart Panel.",customerDescription:"Impresora doméstica sin cartuchos diseñada para reducir el costo por página. Incluye impresión a color, escáner plano y copia, con conexión inalámbrica o USB.",
    specs:[{name:"Funciones",value:"impresión, escaneo y copia",confidence:"confirmed_external",evidence:"Epson oficial"},{name:"Tecnología",value:"Micro Piezo Heat-Free",confidence:"confirmed_external",evidence:"Epson oficial"},{name:"Rendimiento de tinta de reemplazo",value:"hasta 4500 páginas negro / 7500 color",confidence:"confirmed_external",evidence:"Epson; varía según uso"},{name:"Velocidad ISO",value:"10 ppm negro / 5 ppm color",confidence:"confirmed_external",evidence:"Hoja de especificaciones Epson"},{name:"Resolución máxima de impresión",value:"5760 × 1440 dpi optimizados",confidence:"confirmed_external",evidence:"Epson"},{name:"Resolución óptica de escaneo",value:"1200 × 2400 dpi",confidence:"confirmed_external",evidence:"Epson"},{name:"Entrada de papel",value:"100 hojas",confidence:"confirmed_external",evidence:"Epson"},{name:"Conectividad",value:"Wi‑Fi, Wi‑Fi Direct y USB",confidence:"confirmed_external",evidence:"Epson"},{name:"Impresión automática a doble cara",value:"no",confidence:"confirmed_external",evidence:"Epson"},{name:"ADF",value:"no",confidence:"confirmed_external",evidence:"Epson"},{name:"Garantía NEXO",value:"5 días por fallos del equipo",confidence:"confirmed_nexo",evidence:"Condición suministrada"}],
    faq:[{question:"¿Usa cartuchos?",answer:"No. Utiliza botellas de tinta compatibles con su sistema EcoTank.",audience:"customer",confidence:"confirmed_external"},{question:"¿Imprime por ambos lados automáticamente?",answer:"No; el dúplex es manual.",audience:"customer",confidence:"confirmed_external"},{question:"¿Incluye tinta?",answer:"La foto muestra botellas Epson 522, pero NEXO debe confirmar físicamente el contenido exacto de esta unidad antes de prometerlo.",audience:"gestora",confidence:"probable"},{question:"¿Sirve para sublimación?",answer:"Epson la vende para tinta original de inyección. Convertirla a sublimación no forma parte de la especificación ni garantía confirmada.",audience:"customer",confidence:"confirmed_external"}],
    sources:[{sourceType:"physical_photo",title:"Foto suministrada de Epson ET-2400",supports:["modelo","tanques","botellas visibles"],confidence:"confirmed_nexo"},{sourceType:"manufacturer",title:"Epson EcoTank ET-2400",url:"https://epson.com/For-Home/Printers/Inkjet/EcoTank-ET-2400-Wireless-Color-All-in-One-Cartridge-Free-Supertank-Printer-with-Scan-and-Copy/p/C11CJ67201",supports:["funciones","rendimiento","conectividad","papel","velocidad","resolución"],confidence:"confirmed_external"}],
    salesPlaybook:{benefits:["Ahorro frente a cartuchos","Imprime, escanea y copia","Conexión inalámbrica","Tanques visibles y recargables"],idealCustomer:["Hogares","Estudiantes","Pequeños negocios con volumen moderado"],sellingPoints:["Hasta 4.500 páginas negro y 7.500 color con botellas de reemplazo"],objections:[{objection:"¿Es rápida para una oficina grande?",answer:"Es un modelo doméstico de 10/5 ppm ISO; para alto volumen conviene evaluar una gama superior.",confidence:"confirmed_external"}],warnings:["No prometer ADF ni dúplex automático.","Confirmar tintas incluidas y voltaje de la unidad física."]},gaps:[{question:"¿Incluye el juego completo de tintas 522 y cuál es el voltaje de esta unidad?",requiredEvidence:"Foto de caja, accesorios y placa eléctrica",priority:"high"}]
  },
  {
    id:"pk_samsung_a17_5g_4_128",woocommerceProductId:1137,sku:"NEXO-SAMSUNG-A17-4-128-LB",brand:"Samsung",model:"Galaxy A17 5G",aliases:["Samsung A17","Galaxy A17 5G","A17 4/128"],productType:"Smartphone 5G",confidence:"confirmed_external",
    summary:"Smartphone 5G con pantalla Super AMOLED FHD+ de 6,7 pulgadas a 90 Hz, Exynos 1330, 4/128 GB, cámara principal de 50 MP con OIS y batería de 5.000 mAh.",customerDescription:"Teléfono 5G para uso diario, contenido y fotografía, con pantalla AMOLED, estabilización óptica en la cámara principal y almacenamiento ampliable.",
    specs:[{name:"Pantalla",value:"6,7 pulgadas Super AMOLED FHD+, 90 Hz",confidence:"confirmed_external",evidence:"Samsung oficial"},{name:"Procesador",value:"Exynos 1330, 5 nm",confidence:"confirmed_external",evidence:"Samsung oficial"},{name:"Memoria de esta variante",value:"4 GB RAM / 128 GB",confidence:"confirmed_nexo",evidence:"Oferta del proveedor; confirmar en caja"},{name:"Cámara trasera",value:"50 MP OIS + 5 MP ultra gran angular + 2 MP macro",confidence:"confirmed_external",evidence:"Samsung oficial"},{name:"Cámara frontal",value:"13 MP",confidence:"confirmed_external",evidence:"Samsung oficial"},{name:"Batería",value:"5000",unit:"mAh",confidence:"confirmed_external",evidence:"Samsung oficial"},{name:"Carga",value:"hasta 25 W",confidence:"confirmed_external",evidence:"Samsung oficial; cargador puede venderse aparte"},{name:"Protección",value:"IP54 y Gorilla Glass Victus",confidence:"confirmed_external",evidence:"Samsung oficial"},{name:"Expansión",value:"microSD hasta 2 TB",confidence:"confirmed_external",evidence:"Samsung oficial"},{name:"Sistema de lanzamiento",value:"Android 15 / One UI 7",confidence:"confirmed_external",evidence:"Samsung oficial"},{name:"Garantía NEXO",value:"5 días por fallos del equipo",confidence:"confirmed_nexo",evidence:"Condición suministrada"}],
    faq:[{question:"¿Es 5G?",answer:"Sí, esta ficha corresponde al Galaxy A17 5G; las bandas efectivas dependen de la variante regional y del operador.",audience:"customer",confidence:"confirmed_external"},{question:"¿Tiene estabilización óptica?",answer:"Sí, la cámara principal de 50 MP incorpora OIS.",audience:"customer",confidence:"confirmed_external"},{question:"¿Trae cargador?",answer:"No está confirmado para esta unidad. Samsung puede vender el adaptador por separado según mercado.",audience:"customer",confidence:"unknown"},{question:"¿Se le puede subir el precio?",answer:"No. Esta unidad tiene precio bloqueado por decisión comercial NEXO.",audience:"gestora",confidence:"confirmed_nexo"}],
    sources:[{sourceType:"physical_photo",title:"Imagen suministrada del Samsung A17 Light Blue",supports:["color anunciado","diseño","cámaras"],confidence:"confirmed_nexo"},{sourceType:"manufacturer",title:"Samsung Galaxy A17 5G",url:"https://www.samsung.com/uk/business/smartphones/galaxy-a/galaxy-a17-5g-black-128gb-sm-a176bzkaeub/",supports:["pantalla","cámaras","batería","protección","software"],confidence:"confirmed_external"}],
    salesPlaybook:{benefits:["Pantalla Super AMOLED","5G","OIS en cámara principal","Batería de 5.000 mAh","microSD"],idealCustomer:["Usuarios que quieren buena pantalla y cámara estable","Personas que necesitan 5G y almacenamiento ampliable"],sellingPoints:["Pantalla AMOLED de 90 Hz y OIS en un equipo de gama accesible"],objections:[{objection:"¿Incluye cargador?",answer:"No está confirmado; verificar contenido de la caja antes de cerrar la venta.",confidence:"unknown"}],warnings:["Precio bloqueado: la gestora no puede añadir margen.","Confirmar variante regional, Dual SIM, color y contenido de caja."]},gaps:[{question:"¿Cuál es el código de modelo regional y qué accesorios incluye la caja?",requiredEvidence:"Foto de etiqueta IMEI/modelo y contenido sellado",priority:"high"}]
  },
  {
    id:"pk_revvl_tab2_4_64",woocommerceProductId:1139,sku:"NEXO-REVVL-TAB2-4-64",brand:"T-Mobile",model:"REVVL Tab 2",aliases:["REVVL Tab 2","T-Mobile Tab 2","tablet Revvl 10.1"],productType:"Tablet 5G",confidence:"confirmed_external",
    summary:"Tablet 5G de 10,1 pulgadas HD, Dimensity 6300, 4 GB RAM, 64 GB, microSD hasta 2 TB, batería de 6.000 mAh y altavoces estéreo.",customerDescription:"Tablet conectada para estudio, video, navegación y comunicación, con pantalla amplia, 5G y almacenamiento ampliable.",
    specs:[{name:"Pantalla",value:"10,1 pulgadas HD, 1280 × 800",confidence:"confirmed_external",evidence:"T-Mobile oficial"},{name:"Procesador",value:"MediaTek Dimensity 6300",confidence:"confirmed_external",evidence:"T-Mobile oficial"},{name:"Memoria",value:"4 GB RAM / 64 GB",confidence:"confirmed_external",evidence:"T-Mobile oficial"},{name:"Expansión",value:"microSD hasta 2 TB",confidence:"confirmed_external",evidence:"T-Mobile oficial"},{name:"Batería",value:"6000",unit:"mAh",confidence:"confirmed_external",evidence:"T-Mobile oficial"},{name:"Conectividad",value:"5G, 4G LTE, Wi‑Fi ac, Bluetooth 5.3",confidence:"confirmed_external",evidence:"T-Mobile oficial"},{name:"Puertos",value:"USB-C y 3,5 mm",confidence:"confirmed_external",evidence:"T-Mobile oficial"},{name:"Cámaras",value:"8 MP trasera / 5 MP frontal",confidence:"confirmed_external",evidence:"Ficha técnica publicada"},{name:"Peso",value:"14,56 oz (aprox. 413 g)",confidence:"confirmed_external",evidence:"T-Mobile oficial"},{name:"Garantía NEXO",value:"5 días por fallos del equipo",confidence:"confirmed_nexo",evidence:"Condición suministrada"}],
    faq:[{question:"¿Es Full HD?",answer:"No. La resolución oficial es 1280 × 800, clasificada como HD/WXGA.",audience:"customer",confidence:"confirmed_external"},{question:"¿Funciona con SIM?",answer:"Sí, admite conectividad celular, pero deben confirmarse desbloqueo y compatibilidad de bandas de la unidad disponible con el operador local.",audience:"customer",confidence:"confirmed_external"},{question:"¿Incluye cargador?",answer:"La lista oficial indica cable USB-C, pero no confirma adaptador de pared incluido.",audience:"customer",confidence:"confirmed_external"}],
    sources:[{sourceType:"physical_photo",title:"Foto suministrada de REVVL Tab 2",supports:["identidad visual","color"],confidence:"confirmed_nexo"},{sourceType:"manufacturer",title:"T-Mobile REVVL Tab 2",url:"https://www.t-mobile.com/tablet/t-mobile-revvl-tab-2",supports:["pantalla","batería","procesador","memoria","conectividad","puertos","contenido"],confidence:"confirmed_external"},{sourceType:"manufacturer",title:"Meet REVVL Tab 2",url:"https://www.t-mobile.com/news/devices/meet-revvl-tab-2",supports:["pantalla","batería","altavoces","5G"],confidence:"confirmed_external"}],
    salesPlaybook:{benefits:["Pantalla de 10,1 pulgadas","Conectividad 5G","microSD hasta 2 TB","Batería de 6.000 mAh"],idealCustomer:["Estudiantes","Consumo de video y navegación","Usuarios que necesitan conexión móvil"],sellingPoints:["5G y memoria ampliable a precio accesible"],objections:[{objection:"¿La pantalla es FHD?",answer:"No; es HD 1280 × 800. Conviene venderla por conectividad y valor, no como tablet FHD.",confidence:"confirmed_external"}],warnings:["Confirmar desbloqueo y compatibilidad de bandas en Cuba.","No anunciar como FHD."]},gaps:[{question:"¿La unidad está desbloqueada y cuáles son sus bandas/IMEI exactos?",requiredEvidence:"Foto de configuración, caja o consulta IMEI",priority:"high"}]
  },
  {
    id:"pk_miracase_vent_holder",woocommerceProductId:1141,sku:"NEXO-MIRACASE-HOLDER-DARK",brand:"Miracase",model:null,aliases:["Miracase phone holder","soporte Miracase auto","portacelular rejilla"],productType:"Soporte de teléfono para automóvil",confidence:"probable",
    summary:"Soporte Miracase para rejilla horizontal o vertical compatible, con clip metálico, rótula y sujeción para smartphone. El modelo exacto no se distingue en la foto.",customerDescription:"Mantiene el teléfono visible durante la conducción mediante un soporte fijado a una rejilla compatible. Debe comprobarse la forma de la rejilla antes de comprar.",
    specs:[{name:"Montaje observado",value:"clip para rejilla con rótula",confidence:"confirmed_nexo",evidence:"Imagen suministrada"},{name:"Diámetro de la bola mostrado",value:"0,67 pulgadas (1,7 cm)",confidence:"confirmed_nexo",evidence:"Texto de la imagen"},{name:"Altura del conjunto mostrado",value:"3,54 pulgadas (9 cm)",confidence:"confirmed_nexo",evidence:"Texto de la imagen"},{name:"Apertura máxima del gancho mostrada",value:"1,4 pulgadas (3,6 cm)",confidence:"confirmed_nexo",evidence:"Texto de la imagen"},{name:"Rejillas compatibles mostradas",value:"horizontales y verticales",confidence:"confirmed_nexo",evidence:"Gráfico suministrado"},{name:"Rejillas circulares",value:"no compatibles según el gráfico",confidence:"confirmed_nexo",evidence:"Gráfico suministrado"},{name:"Garantía NEXO",value:"5 días por fallos del producto",confidence:"confirmed_nexo",evidence:"Condición suministrada"}],
    faq:[{question:"¿Sirve para cualquier automóvil?",answer:"No. La imagen confirma rejillas horizontales y verticales compatibles, pero marca rejillas circulares como no compatibles.",audience:"customer",confidence:"confirmed_nexo"},{question:"¿Sirve para cualquier teléfono?",answer:"La publicación lo anuncia como universal, pero el ancho y peso máximos no están documentados. Conviene confirmar el teléfono antes de vender.",audience:"customer",confidence:"probable"},{question:"¿Tiene imán?",answer:"La fotografía muestra brazos de sujeción, no un sistema magnético confirmado.",audience:"customer",confidence:"confirmed_nexo"}],
    sources:[{sourceType:"physical_photo",title:"Gráfico suministrado del soporte Miracase",supports:["montaje","medidas mostradas","rejillas compatibles","rejillas no compatibles"],confidence:"confirmed_nexo"}],
    salesPlaybook:{benefits:["Teléfono visible durante la conducción","Instalación compacta","Ajuste por rótula","Sujeción mecánica"],idealCustomer:["Conductores con rejillas horizontales o verticales compatibles"],sellingPoints:["Clip metálico y ajuste de ángulo"],objections:[{objection:"¿Sirve para mi carro?",answer:"Solicita una foto de la rejilla; las circulares aparecen como no compatibles.",confidence:"confirmed_nexo"}],warnings:["No afirmar compatibilidad universal.","No confirmar modelo, ancho o peso máximo sin empaque."]},gaps:[{question:"¿Cuál es el modelo exacto y el rango de ancho/peso del teléfono?",requiredEvidence:"Foto de caja, manual o etiqueta de modelo",priority:"high"}]
  }
];
