import type { PriceCalculation, ProductAnalysis, ProductCopy, ProductResearch } from "./types";
import { validateProductCopyForPublication } from "./product-content";

function config(){const url=process.env.WOOCOMMERCE_URL?.replace(/\/$/,"");const key=process.env.WOOCOMMERCE_CONSUMER_KEY;const secret=process.env.WOOCOMMERCE_CONSUMER_SECRET;if(!url||!key||!secret)throw new Error("WooCommerce REST credentials are not configured");return {url,key,secret};}
async function woo(path:string,init:RequestInit={}){const c=config();const u=new URL(`${c.url}/wp-json/wc/v3${path}`);u.searchParams.set("consumer_key",c.key);u.searchParams.set("consumer_secret",c.secret);const response=await fetch(u,{...init,headers:{"Content-Type":"application/json",...(init.headers??{})},signal:AbortSignal.timeout(60_000),cache:"no-store"});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(`WooCommerce ${path} failed (${response.status})`);return body;}
export function wooConfigured(){return Boolean(process.env.WOOCOMMERCE_URL&&process.env.WOOCOMMERCE_CONSUMER_KEY&&process.env.WOOCOMMERCE_CONSUMER_SECRET);}
export async function listWooProducts(params:{search?:string;category?:string;page?:number;perPage?:number}={}){const q=new URLSearchParams({status:"publish",per_page:String(Math.min(params.perPage??24,50)),page:String(params.page??1)});if(params.search)q.set("search",params.search);if(params.category)q.set("category",params.category);return woo(`/products?${q}`);}
export async function getWooProduct(id:number){return woo(`/products/${id}`);}
export async function getWooOrder(id:number){return woo(`/orders/${id}`);}
export async function updateWooOrder(id:number,input:Record<string,unknown>){return woo(`/orders/${id}`,{method:"PUT",body:JSON.stringify(input)});}
export async function createWooDraft(input:{captureId:string;commerceId:string;analysis:ProductAnalysis;research:ProductResearch;copy:ProductCopy;price:PriceCalculation;imageIds?:number[]}){
  const copyErrors=validateProductCopyForPublication(input.copy);if(copyErrors.length)throw new Error(`La ficha no supera el control editorial: ${copyErrors.join(" ")}`);
  const description=`<p>${input.copy.description}</p><h2>Beneficios</h2><ul>${input.copy.benefits.map(x=>`<li>${escapeHtml(x)}</li>`).join("")}</ul><h2>Especificaciones</h2><ul>${input.copy.specifications.map(x=>`<li><strong>${escapeHtml(x.name)}:</strong> ${escapeHtml(x.value)}</li>`).join("")}</ul>`;
  return woo("/products",{method:"POST",body:JSON.stringify({name:input.copy.title,type:"simple",status:"draft",slug:input.copy.slug,sku:input.copy.sku,regular_price:input.price.finalPrice.toFixed(2),description,short_description:input.copy.shortDescription,manage_stock:false,stock_status:"instock",images:(input.imageIds??[]).map(id=>({id})),meta_data:[{key:"nexo_capture_id",value:input.captureId},{key:"commerce_id",value:input.commerceId},{key:"nexo_verified_at",value:new Date().toISOString()},{key:"nexo_research_sources",value:input.research.sources.map(s=>s.url)},{key:"nexo_price_rule_id",value:input.price.ruleId},{key:"nexo_availability_confirmation",value:"required"}]})});
}
export async function publishWooProduct(id:number){const product=await getWooProduct(id);const errors=[] as string[];if(!String(product.short_description||"").replace(/<[^>]+>/g,"").trim())errors.push("descripción breve");if(!String(product.description||"").replace(/<[^>]+>/g,"").trim())errors.push("descripción detallada");if(!/<h[1-6][^>]*>\s*Especificaciones\s*<\/h[1-6]>/i.test(String(product.description||""))&&!Array.isArray(product.attributes))errors.push("especificaciones");if(errors.length)throw new Error(`No se puede publicar: faltan ${errors.join(", ")}.`);return woo(`/products/${id}`,{method:"PUT",body:JSON.stringify({status:"publish"})});}
function escapeHtml(value:string){return value.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]!));}
