"use client";import Link from "next/link";import { FormEvent, useEffect, useState } from "react";
type Capture={id:string;status:string;analysis?:any;research?:any;product_copy?:any;price_calculation?:any;woocommerce_product_id?:number;error_message?:string;created_at:string};
const labels:Record<string,string>={uploaded:"Fotografías recibidas",analyzing:"Leyendo fotografías",needs_evidence:"Falta evidencia",researching:"Investigando",awaiting_review:"Listo para revisar",approved:"Aprobado",woocommerce_draft:"Borrador en WooCommerce",published:"Publicado",failed:"Requiere atención"};
export default function ProductCaptureClient(){const [files,setFiles]=useState<File[]>([]);const [capture,setCapture]=useState<Capture|null>(null);const [recent,setRecent]=useState<Capture[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 async function refresh(){const r=await fetch("/api/studio/products/captures");if(r.ok){const d=await r.json();setRecent(d.captures)}}useEffect(()=>{const timer=window.setTimeout(()=>void refresh(),0);return()=>window.clearTimeout(timer)},[]);
 async function submit(e:FormEvent){e.preventDefault();setError("");if(!files.length)return;setBusy(true);try{const form=new FormData();files.forEach(f=>form.append("images",f));form.set("commerceId","nexo");const r=await fetch("/api/studio/products/captures",{method:"POST",body:form});const d=await r.json();if(!r.ok)throw new Error(d.error);setCapture({id:d.captureId,status:d.status,created_at:new Date().toISOString()});const p=await fetch(`/api/studio/products/captures/${d.captureId}/process`,{method:"POST"});const pd=await p.json();if(!p.ok)throw new Error(pd.error);setCapture(pd.capture);void refresh()}catch(e){setError(e instanceof Error?e.message:"No se pudo procesar la captura.")}finally{setBusy(false)}}
 async function createDraft(){if(!capture)return;setBusy(true);setError("");try{const r=await fetch(`/api/studio/products/captures/${capture.id}/woocommerce`,{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.error);const detail=await fetch(`/api/studio/products/captures/${capture.id}`).then(x=>x.json());setCapture(detail.capture);void refresh()}catch(e){setError(e instanceof Error?e.message:"No se pudo crear el borrador.")}finally{setBusy(false)}}
 return <main className="product-studio"><header><div><span>NEXO STUDIO</span><h1>Captura un producto.</h1><p>Sube fotos reales. NEXO lee la evidencia, busca el modelo exacto, prepara la ficha y detiene la publicación si falta un dato crítico.</p></div><Link href="/studio">Volver a Studio</Link></header>
 <section className="capture-panel"><form onSubmit={submit}><label className="upload-zone"><input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" multiple capture="environment" onChange={e=>setFiles(Array.from(e.target.files??[]).slice(0,8))}/><b>{files.length?`${files.length} foto${files.length===1?"":"s"} seleccionada${files.length===1?"":"s"}`:"Tomar o elegir fotografías"}</b><span>Producto completo, marca/modelo, precio, garantía, placa y accesorios.</span></label>{files.length>0&&<div className="file-chips">{files.map(f=><span key={f.name}>{f.name}</span>)}</div>}<button disabled={busy||!files.length}>{busy?"NEXO está trabajando…":"Analizar producto"}</button></form>{error&&<div className="studio-error"><b>No se pudo completar</b><p>{error}</p></div>}</section>
 {capture&&<section className="capture-result"><div className="result-head"><div><span>{labels[capture.status]||capture.status}</span><h2>{capture.product_copy?.title||capture.analysis?.targetDescription||"Procesando producto"}</h2></div>{capture.analysis?.brand?.confidence!=null&&<b>{Math.round(capture.analysis.brand.confidence*100)}% marca</b>}</div>
 {capture.analysis&&<div className="evidence-grid"><article><small>Marca</small><strong>{capture.analysis.brand.value||"No identificada"}</strong><span>{Math.round(capture.analysis.brand.confidence*100)}% · {capture.analysis.brand.origin}</span></article><article><small>Modelo</small><strong>{capture.analysis.model.value||"No identificado"}</strong><span>{Math.round(capture.analysis.model.confidence*100)}% · {capture.analysis.model.origin}</span></article><article><small>Precio observado</small><strong>{capture.analysis.observedPrice.value?`${capture.analysis.observedPrice.currency||""} ${capture.analysis.observedPrice.value}`:"No legible"}</strong><span>{Math.round(capture.analysis.observedPrice.confidence*100)}% · fotografía</span></article><article><small>Precio NEXO</small><strong>{capture.price_calculation?`${capture.price_calculation.currency} ${capture.price_calculation.finalPrice}`:"Pendiente"}</strong><span>{capture.price_calculation?`Regla ${capture.price_calculation.ruleId}`:"Requiere costo"}</span></article></div>}
 {capture.analysis?.missingCritical?.length>0&&<div className="missing"><b>Antes de publicar necesitamos:</b><ul>{capture.analysis.requestedEvidence.map((x:string)=><li key={x}>{x}</li>)}</ul></div>}
 {capture.research&&<div className="research"><h3>Investigación {capture.research.status}</h3><p>{capture.research.summary}</p><ul>{capture.research.sources?.map((s:any)=><li key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a><span>{s.sourceType}</span></li>)}</ul></div>}
 {capture.product_copy&&<div className="copy-preview"><h3>Ficha preparada</h3><p>{capture.product_copy.shortDescription}</p><details><summary>Ver descripción y SEO</summary><p>{capture.product_copy.description}</p><small>{capture.product_copy.metaDescription}</small></details></div>}
 <button className="draft-button" disabled={busy||capture.status!=="awaiting_review"} onClick={createDraft}>{capture.woocommerce_product_id?`Borrador #${capture.woocommerce_product_id} creado`:"Crear borrador en WooCommerce"}</button></section>}
 <section className="recent-captures"><h2>Capturas recientes</h2>{recent.length===0?<p>Aún no hay capturas.</p>:recent.map(x=><button key={x.id} onClick={async()=>{const d=await fetch(`/api/studio/products/captures/${x.id}`).then(r=>r.json());setCapture(d.capture)}}><span>{x.product_copy?.title||x.analysis?.targetDescription||x.id}</span><b>{labels[x.status]||x.status}</b></button>)}</section></main>}
