import {redirect} from "next/navigation";
import {currentCommercialActor} from "../../../lib/commercial/auth";
import {adminOverview} from "../../../lib/commercial/admin-overview";
import AdminNav from "../AdminNav";
import "../admin.css";
export const dynamic="force-dynamic";
export const metadata={title:"Pedidos | NEXO Admin"};
const labels:Record<string,string>={pending:"Pendiente",processing:"Procesando",on_hold:"En espera",completed:"Completado",cancelled:"Cancelado",refunded:"Reembolsado",failed:"Fallido"};
export default async function Page(){const actor=await currentCommercialActor();if(!actor||actor.role!=="admin")redirect("/admin/login");const data=await adminOverview();return <main className="admin-shell"><header className="admin-top"><div><img src="/brand/nexo-logo-001g.png" alt="NEXO"/><span>ADMIN</span></div><a href="/">Ver tienda</a></header><AdminNav/><div className="admin-wrap"><section className="admin-hero compact"><span>PEDIDOS</span><h1>Operación de pedidos</h1><p>Encuentra qué requiere atención y abre cada pedido para ver origen, entrega y comisión.</p></section><section className="admin-order-filters" aria-label="Estados"><a href="#todos">Todos <b>{data.orders.length}</b></a><a href="#pendientes">Pendientes <b>{data.orders.filter(o=>["pending","on_hold"].includes(o.status)).length}</b></a><a href="#procesando">Procesando <b>{data.orders.filter(o=>o.status==="processing").length}</b></a><a href="#completados">Completados <b>{data.orders.filter(o=>o.status==="completed").length}</b></a></section><section className="admin-panel" id="todos"><div className="admin-heading"><div><span>RECIENTES</span><h2>Últimos pedidos</h2></div></div><div className="admin-orders">{data.orders.length?data.orders.map(o=><a className="admin-order-link" key={o.id} href={`/admin/pedidos/${o.id}`}><article><div className="order-main"><div><small>#{o.id} · {new Date(o.date).toLocaleString("es-CU",{dateStyle:"short",timeStyle:"short"})}</small><h3>{o.customer}</h3><p>{o.items.map((x:any)=>`${x.quantity}× ${x.name}`).join(" · ")}</p></div><div className="order-total"><b>{o.total.toFixed(2)} {o.currency}</b><span>{labels[o.status]||o.status}</span></div></div><div className="order-context"><span>{o.gestora?`Gestora: ${o.gestora}`:"Venta directa"}</span><span>{o.deliveryMode||"Entrega por confirmar"}</span>{o.locality&&<span>{o.locality}</span>}</div></article></a>):<div className="admin-empty">No hay pedidos recientes.</div>}</div></section></div></main>}
