"use client";
import Image from "next/image";
import Link from "next/link";
import { KeyboardEvent, useEffect, useMemo, useRef, useState } from "react";
import { catalogImageFor } from "../../lib/commerce/catalog-images";
import { familyForProduct, STOREFRONT_CATEGORIES, type StorefrontCategory } from "../../lib/commerce/storefront-categories";

type WooProduct={id:number;name:string;sku?:string;price:string;stock_status:string;images:Array<{src:string;alt:string}>;categories:Array<{id:number;name:string}>;search_text?:string};
const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("es");
const sectionCopy:Record<string,string>={"energia-y-respaldo":"Soluciones para los apagones","cocina-y-electrodomesticos":"Equipa tu cocina","descanso-y-dormitorio":"Descanso y confort","tecnologia":"Tecnología para cada día","muebles-y-organizacion":"Organiza tu hogar","movilidad":"Movilidad para Cuba","otros":"Descubre algo nuevo"};

export default function MarketplaceClient(){
 const[products,setProducts]=useState<WooProduct[]>([]),[query,setQuery]=useState(""),[category,setCategory]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[drawer,setDrawer]=useState(false),[activeSuggestion,setActiveSuggestion]=useState(-1),[slide,setSlide]=useState(0),[visibleLimit,setVisibleLimit]=useState(16),[refCode]=useState(()=>typeof window==="undefined"?"":new URLSearchParams(window.location.search).get("ref")?.trim()||""),searchRef=useRef<HTMLInputElement>(null),closeRef=useRef<HTMLButtonElement>(null);
 useEffect(()=>{void fetch("/api/marketplace/products",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"No pudimos cargar los productos.");setProducts(d.products)}).catch(e=>setError(e instanceof Error?e.message:"No pudimos cargar los productos.")).finally(()=>setLoading(false))},[]);
 useEffect(()=>{document.body.style.overflow=drawer?"hidden":"";if(drawer)closeRef.current?.focus();return()=>{document.body.style.overflow=""}},[drawer]);
 useEffect(()=>{const key=(e:globalThis.KeyboardEvent)=>{if(e.key==="Escape")setDrawer(false)};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[]);
 const families=useMemo(()=>STOREFRONT_CATEGORIES.filter(f=>f.enabled).sort((a,b)=>a.order-b.order),[]),clean=normalize(query.trim()),withRef=(path:string)=>`${path}${refCode?`${path.includes("?")?"&":"?"}ref=${encodeURIComponent(refCode)}`:""}`;
 const visible=useMemo(()=>products.filter(p=>(!category||familyForProduct(p).slug===category)&&(!clean||normalize(`${p.search_text||p.name} ${p.sku||""} ${p.categories.map(c=>c.name).join(" ")}`).includes(clean))),[products,category,clean]);
 const suggestions=clean.length>=2?visible.slice(0,6):[];
 const groups=useMemo(()=>families.map(f=>({family:f,products:products.filter(p=>familyForProduct(p).slug===f.slug)})).filter(g=>g.products.length),[families,products]);
 const featured=products.slice(0,10),under25=products.filter(p=>Number(p.price)>0&&Number(p.price)<25).slice(0,8),campaigns=[groups[0],groups[1],groups[2]].filter(Boolean);
 function choose(slug:string){setCategory(slug);setVisibleLimit(16);setDrawer(false);requestAnimationFrame(()=>document.getElementById("productos")?.scrollIntoView({behavior:"smooth"}))}
 function submit(){if(suggestions[0])window.location.assign(withRef(`/producto/${suggestions[0].id}`));else document.getElementById("productos")?.scrollIntoView({behavior:"smooth"})}
 return <main className="marketplace-shell">
  <header className="market-header">
   <div className="market-topbar"><button className="menu-trigger" type="button" onClick={()=>setDrawer(true)} aria-label="Abrir menú"><span/><span/><span/></button><Link className="market-brand" href={withRef("/")} aria-label="NEXO — Inicio"><Image src="/brand/nexo-logo-001g.png" width={380} height={140} alt="NEXO" priority/></Link><div className="market-account"><Link href="/impulsa/login"><small>Para gestoras</small><b>Impulsa</b></Link><Link className="cart-button" href={withRef("/carrito")} aria-label="Ver carrito"><span aria-hidden="true">🛒</span><b>Carrito</b></Link></div></div>
   <section className="market-search" aria-label="Buscar productos"><label htmlFor="market-search">Buscar en NEXO</label><div className="search-box"><input id="market-search" type="search" role="combobox" aria-autocomplete="list" aria-expanded={suggestions.length>0} aria-controls="market-search-suggestions" aria-activedescendant={activeSuggestion>=0?`market-suggestion-${suggestions[activeSuggestion]?.id}`:undefined} ref={searchRef} value={query} onChange={e=>{setQuery(e.target.value);setActiveSuggestion(-1)}} onKeyDown={(e:KeyboardEvent<HTMLInputElement>)=>{if(e.key==="ArrowDown"){e.preventDefault();setActiveSuggestion(x=>Math.min(x+1,suggestions.length-1))}if(e.key==="ArrowUp"){e.preventDefault();setActiveSuggestion(x=>Math.max(x-1,0))}if(e.key==="Escape"){setQuery("");setActiveSuggestion(-1)}if(e.key==="Enter"){e.preventDefault();if(activeSuggestion>=0&&suggestions[activeSuggestion])window.location.assign(withRef(`/producto/${suggestions[activeSuggestion].id}`));else submit()}}} placeholder="Buscar en NEXO" autoComplete="off"/><button type="button" onClick={submit} aria-label="Buscar">⌕</button></div>
    {suggestions.length>0&&<ul id="market-search-suggestions" role="listbox" className="search-suggestions">{suggestions.map((p,i)=><li id={`market-suggestion-${p.id}`} role="option" aria-selected={activeSuggestion===i} key={p.id}><Link href={withRef(`/producto/${p.id}`)}><img src={catalogImageFor(p)||"/brand/nexo-symbol.png"} alt=""/><span><b>{p.name}</b><small>{familyForProduct(p).label}</small></span><strong>{p.price} USD</strong></Link></li>)}</ul>}
   </section>
   <nav className="quick-links" aria-label="Accesos rápidos"><button onClick={()=>choose("")}>Ofertas</button>{families.slice(0,7).map(f=><button key={f.id} onClick={()=>choose(f.slug)}>{f.label}</button>)}<button onClick={()=>setDrawer(true)}>Ver todo</button></nav>
   <button className="delivery-bar" type="button" onClick={()=>document.getElementById("confianza")?.scrollIntoView({behavior:"smooth"})}><span aria-hidden="true">⌖</span><span><small>Entrega coordinada</small><b>Elige dónde recibir tu pedido</b></span><span>›</span></button>
  </header>

  {drawer&&<div className="drawer-layer" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setDrawer(false)}}><aside className="market-drawer" role="dialog" aria-modal="true" aria-label="Explora NEXO"><div className="drawer-head"><div><small>Explora</small><strong>NEXO</strong></div><button ref={closeRef} type="button" onClick={()=>setDrawer(false)} aria-label="Cerrar menú">×</button></div><nav><button onClick={()=>choose("")}>⌂ Inicio</button><h2>Categorías principales</h2>{families.map(f=><button key={f.id} onClick={()=>choose(f.slug)}>{f.label}<span>›</span></button>)}<hr/><Link href={withRef("/carrito")}>Mi carrito <span>›</span></Link><a href="https://wa.me/5354056173" target="_blank" rel="noreferrer">Ayuda por WhatsApp <span>›</span></a><Link href="/impulsa/login">Vender con NEXO <span>›</span></Link></nav></aside></div>}

  {!loading&&!error&&campaigns.length>0&&<section className="campaigns" aria-label="Campañas NEXO"><div className="campaign-track" style={{transform:`translateX(-${slide*100}%)`}}>{campaigns.map((g,i)=>{const p=g.products[0],src=catalogImageFor(p);return <article className={`campaign campaign-${i+1}`} key={g.family.id}><div><small>DESCUBRE EN NEXO</small><h1>{sectionCopy[g.family.slug]||g.family.label}</h1><p>Productos seleccionados para resolver lo que necesitas hoy.</p><button type="button" onClick={()=>choose(g.family.slug)}>Ver opciones →</button></div>{src&&<img src={src} alt={p.name}/>}</article>})}</div>{campaigns.length>1&&<div className="campaign-controls">{campaigns.map((_,i)=><button key={i} className={slide===i?"active":""} onClick={()=>setSlide(i)} aria-label={`Ver campaña ${i+1}`}/>)}</div>}</section>}

  <section className="home-content">
   {loading&&<div className="product-state">Preparando tu tienda…</div>}
   {error&&<div className="product-state error" role="alert"><strong>No pudimos cargar la tienda</strong><p>{error}</p></div>}
   {!loading&&!error&&<><CategoryMosaic title="Explora NEXO" groups={groups.slice(0,4)} choose={choose}/>
    <ProductRail title="Productos destacados" products={featured} withRef={withRef}/>
    {groups.slice(0,5).map((g,index)=><section className="discovery-block" key={g.family.id}><CategoryMosaic title={sectionCopy[g.family.slug]||g.family.label} groups={[g,...groups.filter(x=>x.family.id!==g.family.id).slice(index,index+3)].slice(0,4)} choose={choose}/><ProductRail title={g.family.label} products={g.products.slice(0,8)} withRef={withRef}/></section>)}
    {under25.length>0&&<ProductRail title="Productos por menos de 25 USD" products={under25} withRef={withRef}/>}
   </>}
  </section>

  <section id="productos" className="products-section"><header><div><small>CATÁLOGO NEXO</small><h2>{clean?`Resultados para “${query.trim()}”`:families.find(f=>f.slug===category)?.label||"Todos los productos"}</h2></div>{category&&<button onClick={()=>choose("")}>Ver todo</button>}</header>{!loading&&!error&&!visible.length&&<div className="product-state"><strong>No encontramos coincidencias.</strong><button onClick={()=>{setQuery("");choose("");searchRef.current?.focus()}}>Ver productos</button></div>}<div className="product-grid">{visible.slice(0,visibleLimit).map(p=><ProductCard key={p.id} product={p} href={withRef(`/producto/${p.id}`)}/>)}</div>{visible.length>visibleLimit&&<button className="load-more" type="button" onClick={()=>setVisibleLimit(x=>x+16)}>Mostrar más productos</button>}</section>
  <section id="confianza" className="trust-strip"><article><b>Compra clara</b><span>Precio visible antes de confirmar.</span></article><article><b>Entrega coordinada</b><span>Acordamos contigo dónde recibir.</span></article><article><b>Atención NEXO</b><span>Acompañamiento durante tu pedido.</span></article></section>
 </main>
}

function ProductCard({product,href}:{product:WooProduct;href:string}){const src=catalogImageFor(product);return <article className="product-card"><Link href={href}><div className="product-media">{src?<img src={src} alt={product.images?.[0]?.alt||product.name}/>:<Image src="/brand/nexo-symbol.png" width={90} height={90} alt="Producto NEXO"/>}</div><div className="product-info"><h3>{product.name}</h3><strong>{product.price} USD</strong><span>Ver producto</span></div></Link></article>}
function ProductRail({title,products,withRef}:{title:string;products:WooProduct[];withRef:(p:string)=>string}){if(!products.length)return null;return <section className="product-rail"><header><h2>{title}</h2><a href="#productos">Ver más</a></header><div>{products.map(p=><ProductCard key={p.id} product={p} href={withRef(`/producto/${p.id}`)}/>)}</div></section>}
function CategoryMosaic({title,groups,choose}:{title:string;groups:Array<{family:StorefrontCategory;products:WooProduct[]}>;choose:(s:string)=>void}){if(!groups.length)return null;return <section className="category-mosaic"><h2>{title}</h2><div>{groups.slice(0,4).map(g=>{const p=g.products[0],src=p&&catalogImageFor(p);return <button key={g.family.id} onClick={()=>choose(g.family.slug)}>{src?<img src={src} alt=""/>:<CategoryIcon family={g.family}/>}<span>{g.family.label}</span></button>})}</div><button className="see-more" onClick={()=>choose("")}>Ver más</button></section>}
function CategoryIcon({family}:{family:StorefrontCategory}){return <span className="category-fallback" aria-hidden="true">{family.label.slice(0,1)}</span>}
