"use client";
import Image from "next/image";import Link from "next/link";import { FormEvent, useEffect, useState } from "react";
type WooProduct={id:number;name:string;slug:string;price:string;regular_price:string;sale_price:string;stock_status:string;images:Array<{src:string;alt:string}>;categories:Array<{id:number;name:string}>;meta_data?:Array<{key:string;value:unknown}>};
function availability(p:WooProduct){return p.meta_data?.some(m=>m.key==="nexo_availability_confirmation"&&m.value==="required")?"Confirmamos disponibilidad":p.stock_status==="instock"?"Disponible":"Agotado";}
export default function MarketplaceClient(){const [products,setProducts]=useState<WooProduct[]>([]);const [query,setQuery]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [storeUrl,setStoreUrl]=useState("");
 async function load(search=""){setLoading(true);setError("");try{const r=await fetch(`/api/marketplace/products${search?`?search=${encodeURIComponent(search)}`:""}`);const d=await r.json();if(!r.ok)throw new Error(d.error||"No se pudo cargar el catálogo.");setProducts(d.products);setStoreUrl(d.storeUrl||"");}catch(e){setError(e instanceof Error?e.message:"No se pudo cargar el catálogo.");}finally{setLoading(false)}}useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[]);
 function submit(e:FormEvent){e.preventDefault();void load(query)}
 return <main className="marketplace-shell"><header className="market-header"><Link href="/" aria-label="NEXO Marketplace"><Image src="/brand/nexo-logo.png" width={210} height={75} alt="NEXO" priority/></Link><div className="market-actions"><Link href="/studio">Studio</Link>{storeUrl&&<a className="market-cart" href={`${storeUrl}/cart/`}>Carrito</a>}</div></header>
 <section className="market-search"><form onSubmit={submit}><label className="sr-only" htmlFor="market-search">Buscar productos</label><input id="market-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="¿Qué estás buscando?"/><button>Buscar</button></form><nav aria-label="Categorías"><button onClick={()=>{setQuery("");void load()}}>Todo</button><button onClick={()=>{setQuery("hogar");void load("hogar")}}>Hogar</button><button onClick={()=>{setQuery("tecnología");void load("tecnología")}}>Tecnología</button><button onClick={()=>{setQuery("electrodoméstico");void load("electrodoméstico")}}>Electro</button><button onClick={()=>{setQuery("ventilador");void load("ventilador")}}>Energía</button></nav></section>
 <section className="market-hero"><div><span>NEXO Marketplace</span><h1>Lo que buscas,<br/><em>más cerca.</em></h1><p>Productos seleccionados, compra acompañada y entrega coordinada.</p><a href="#productos">Ver productos</a></div><div className="hero-orb" aria-hidden="true"/></section>
 <section id="productos" className="products-section"><header><div><span>Catálogo</span><h2>Productos para ti</h2></div>{!loading&&!error&&<p>{products.length} productos</p>}</header>{loading&&<div className="product-state">Cargando catálogo…</div>}{error&&<div className="product-state error"><strong>Catálogo pendiente de conexión</strong><p>{error}</p></div>}{!loading&&!error&&products.length===0&&<div className="product-state">No encontramos productos con esa búsqueda.</div>}
 <div className="product-grid">{products.map(p=><article className="product-card" key={p.id}><Link href={`/producto/${p.id}`}><div className="product-media">{p.images?.[0]?.src?<img src={p.images[0].src} alt={p.images[0].alt||p.name}/>:<div className="no-photo">NEXO</div>}<span>{availability(p)}</span></div><div className="product-info"><small>{p.categories?.[0]?.name||"NEXO"}</small><h3>{p.name}</h3><div className="price-row"><div>{p.sale_price&&<del>${p.regular_price}</del>}<strong>${p.price}</strong></div><span className="add-symbol">＋</span></div></div></Link></article>)}</div></section>
 <section className="market-benefits"><div><b>Compra segura</b><span>Pedido oficial en WooCommerce</span></div><div><b>Entrega coordinada</b><span>Mensajería calculada por separado</span></div><div><b>Acompañamiento</b><span>Soporte humano durante tu compra</span></div></section>
 <footer><Image src="/brand/nexo-logo.png" width={168} height={60} alt="NEXO"/><p>Lo que buscas, más cerca.</p><nav><Link href="/contacto">Contacto</Link><Link href="/studio">NEXO Studio</Link></nav></footer></main>}
