"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";

type CartItem = { key:string; id:number; name:string; quantity:number; images:Array<{src:string;alt:string}>; prices:{price:string;currency_symbol:string;currency_minor_unit:number}; totals:{line_total:string}; quantity_limits?:{minimum:number;maximum:number;multiple_of:number} };
type Cart = { items:CartItem[]; totals:{total_items:string;total_price:string;currency_symbol:string;currency_minor_unit:number} };
function money(value:string,symbol:string,minor:number){return `${symbol}${(Number(value)/(10**minor)).toLocaleString("en-US",{minimumFractionDigits:0,maximumFractionDigits:2})}`;}

export default function CartClient({initialReferral}:{initialReferral:string}){
  const [cart,setCart]=useState<Cart|null>(null),[referral,setReferral]=useState(initialReferral),[loading,setLoading]=useState(true),[updating,setUpdating]=useState(""),[error,setError]=useState("");
  const request=useCallback(async(action?:object)=>{setError("");const endpoint=action?"/api/commerce/cart":`/api/commerce/cart?nexo_session=${Date.now()}`;const response=await fetch(endpoint,action?{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(action)}:{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"No se pudo actualizar el carrito.");setCart(data.cart);setReferral(data.referral||initialReferral);},[initialReferral]);
  useEffect(()=>{const timer=window.setTimeout(()=>{void request().catch((caught)=>setError(caught instanceof Error?caught.message:"No se pudo recuperar el carrito.")).finally(()=>setLoading(false));},0);return()=>window.clearTimeout(timer);},[request]);
  async function update(action:object,key:string){setUpdating(key);try{await request(action);}catch(caught){setError(caught instanceof Error?caught.message:"No se pudo actualizar el carrito.");}finally{setUpdating("");}}
  const query=useMemo(()=>referral?`?ref=${encodeURIComponent(referral)}`:"",[referral]);
  if(loading)return <section className="cart-state" aria-live="polite"><div className="cart-spinner"/><h1>Cargando tu carrito…</h1></section>;
  if(error&&!cart)return <section className="cart-state error"><h1>No pudimos recuperar tu carrito</h1><p>{error}</p><button onClick={()=>{setLoading(true);void request().catch(caught=>setError(caught instanceof Error?caught.message:"Error de conexión.")).finally(()=>setLoading(false));}}>Intentar de nuevo</button></section>;
  if(!cart?.items.length)return <section className="cart-state"><span className="empty-bag">N</span><h1>Tu carrito está vacío</h1><p>Explora el catálogo y guarda aquí los productos que quieres consultar o comprar.</p><Link href={`/marketplace${query}`}>Ver productos</Link></section>;
  const {currency_symbol:symbol,currency_minor_unit:minor}=cart.totals;
  return <div className="cart-shell"><section className="cart-list"><header><div><span>Tu selección</span><h1>Carrito NEXO</h1></div><p>{cart.items.length} {cart.items.length===1?"producto":"productos"}</p></header>{error&&<div className="cart-error" role="alert">{error}</div>}{cart.items.map(item=>{const limits=item.quantity_limits??{minimum:1,maximum:99,multiple_of:1},busy=updating===item.key;return <article className={`cart-item${busy?" is-updating":""}`} key={item.key}><Link className="cart-image" href={`/producto/${item.id}${query}`}>{item.images?.[0]?<img src={item.images[0].src} alt={item.images[0].alt||item.name}/>:<span>NEXO</span>}</Link><div className="cart-product"><Link href={`/producto/${item.id}${query}`}>{item.name}</Link><strong>{money(item.prices.price,item.prices.currency_symbol,item.prices.currency_minor_unit)}</strong><div className="quantity-control"><button aria-label={`Reducir cantidad de ${item.name}`} disabled={busy||item.quantity<=limits.minimum} onClick={()=>update({action:"update",key:item.key,quantity:item.quantity-limits.multiple_of},item.key)}>−</button><span aria-label={`Cantidad ${item.quantity}`}>{item.quantity}</span><button aria-label={`Aumentar cantidad de ${item.name}`} disabled={busy||item.quantity>=limits.maximum} onClick={()=>update({action:"update",key:item.key,quantity:item.quantity+limits.multiple_of},item.key)}>+</button></div><button className="remove-item" disabled={busy} onClick={()=>update({action:"remove",key:item.key},item.key)}>Eliminar</button></div><strong className="line-total">{money(item.totals.line_total,symbol,minor)}</strong></article>})}<Link className="continue-shopping" href={`/marketplace${query}`}>← Continuar comprando</Link></section><aside className="cart-summary"><span>Resumen</span><div><p>Subtotal</p><strong>{money(cart.totals.total_items,symbol,minor)}</strong></div><p className="delivery-note">La mensajería se calcula por separado según el destino y el volumen.</p><div className="cart-total"><p>Total de productos</p><strong>{money(cart.totals.total_price,symbol,minor)}</strong></div><button disabled>Continuar al checkout</button><small>El checkout propio de NEXO se habilitará en el siguiente paso. Tu carrito queda guardado.</small>{referral&&<p className="referral-ok">✓ Atribución conservada: {referral}</p>}</aside></div>;
}
