"use client";
import {useState} from "react";

type Product={id:number;name:string;sku:string;type:string;price:string;regular_price:string;stock_quantity:number|null;stock_status:string;manage_stock:boolean;status:string;images?:Array<{src?:string}>};

export default function ProductInventoryClient({products}:{products:Product[]}){
 const[items,setItems]=useState(products);const[busy,setBusy]=useState<string|null>(null);const[message,setMessage]=useState<string>("");
 async function update(product:Product,action:"stock"|"price"|"status",value:number|string){const key=`${product.id}:${action}`;setBusy(key);setMessage("");try{const body:any={productId:product.id,action};if(action==="stock")body.quantity=Number(value);if(action==="price")body.price=Number(value);if(action==="status")body.status=String(value);const r=await fetch("/api/admin/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error||"No se pudo actualizar.");setItems(current=>current.map(p=>p.id!==product.id?p:action==="stock"?{...p,manage_stock:true,stock_quantity:data.product.stockQuantity,stock_status:data.product.stockStatus}:action==="price"?{...p,price:data.product.price,regular_price:data.product.regularPrice}:{...p,status:data.product.status}));setMessage(`${product.name}: cambio guardado en WooCommerce.`);}catch(e){setMessage(e instanceof Error?e.message:"No se pudo actualizar.");}finally{setBusy(null)}}
 return <>{message&&<div className="admin-action-feedback" role="status">{message}</div>}<div className="admin-product-grid">{items.map(product=>{const variable=product.type==="variable";return <article className="admin-product-card" key={product.id}><div className="admin-product-head">{product.images?.[0]?.src?<img src={product.images[0].src} alt={product.name}/>:<div className="admin-product-placeholder">📦</div>}<div><small>{product.sku||`#${product.id}`}</small><h3>{product.name}</h3><span>{product.status==="publish"?"Publicado":"Borrador"} · {variable?"Con variantes":product.stock_status==="instock"?"Disponible":"Agotado"}</span></div></div>{variable?<a className="admin-product-status" href={`/admin/productos/${product.id}`} style={{display:"grid",placeItems:"center",textDecoration:"none"}}>Gestionar variantes</a>:<><div className="admin-product-controls"><label>Precio USD<div><input type="number" min="0" step="0.01" defaultValue={product.regular_price||product.price||"0"} id={`price-${product.id}`}/><button disabled={busy===`${product.id}:price`} onClick={()=>{const el=document.getElementById(`price-${product.id}`) as HTMLInputElement;update(product,"price",el.value)}}>Guardar</button></div></label><label>Existencia<div><input type="number" min="0" step="1" placeholder={product.manage_stock?"0":"Sin control"} defaultValue={product.stock_quantity??undefined} id={`stock-${product.id}`}/><button disabled={busy===`${product.id}:stock`} onClick={()=>{const el=document.getElementById(`stock-${product.id}`) as HTMLInputElement;update(product,"stock",el.value)}}>Guardar</button></div></label></div><button className="admin-product-status" disabled={busy===`${product.id}:status`} onClick={()=>{const next=product.status==="publish"?"draft":"publish";if(window.confirm(next==="publish"?"¿Publicar este producto?":"¿Pasar este producto a borrador?"))update(product,"status",next)}}>{product.status==="publish"?"Pasar a borrador":"Publicar producto"}</button></>}</article>})}</div></>;
}