-- NEXO Business schema-v0 DESIGN ONLY; do not apply to production.
create extension if not exists pgcrypto;
create table nb_businesses(id uuid primary key,name text not null,slug text unique not null,created_at timestamptz not null default now());
create table nb_branches(id uuid primary key,business_id uuid not null references nb_businesses(id),name text not null,timezone text not null default 'America/Havana',active boolean not null default true);
create table nb_devices(id uuid primary key,business_id uuid not null references nb_businesses(id),branch_id uuid references nb_branches(id),label text not null,platform text not null check(platform in('android','windows','web')),last_seen_at timestamptz);
create table nb_memberships(id uuid primary key,business_id uuid not null references nb_businesses(id),user_id uuid not null,role text not null check(role in('owner','admin','manager','cashier','stock','viewer')),active boolean not null default true,unique(business_id,user_id));
create table nb_categories(id uuid primary key,business_id uuid not null references nb_businesses(id),name text not null,parent_id uuid references nb_categories(id),active boolean not null default true,version bigint not null default 1);
create table nb_products(id uuid primary key,business_id uuid not null references nb_businesses(id),category_id uuid references nb_categories(id),sku text,name text not null,unit text not null default 'unit',active boolean not null default true,version bigint not null default 1,unique(business_id,sku));
create table nb_barcodes(id uuid primary key,business_id uuid not null references nb_businesses(id),product_id uuid not null references nb_products(id),code text not null,format text,unique(business_id,code));
create table nb_prices(id uuid primary key,business_id uuid not null references nb_businesses(id),product_id uuid not null references nb_products(id),currency text not null,amount numeric(18,4) not null check(amount>=0),valid_from timestamptz not null default now(),valid_to timestamptz,version bigint not null default 1);
create table nb_external_refs(id uuid primary key,business_id uuid not null references nb_businesses(id),entity_type text not null,entity_id uuid not null,system text not null,external_id text not null,unique(business_id,system,entity_type,external_id));
create table nb_inventory_locations(id uuid primary key,business_id uuid not null references nb_businesses(id),branch_id uuid references nb_branches(id),name text not null);
create table nb_inventory_movements(id uuid primary key,business_id uuid not null references nb_businesses(id),location_id uuid not null references nb_inventory_locations(id),product_id uuid not null references nb_products(id),quantity_delta numeric(18,4) not null check(quantity_delta<>0),reason text not null,source_type text not null,source_id uuid,device_id uuid references nb_devices(id),actor_user_id uuid,occurred_at timestamptz not null);
create index nb_inventory_movements_lookup on nb_inventory_movements(business_id,location_id,product_id,occurred_at);
create table nb_cash_shifts(id uuid primary key,business_id uuid not null references nb_businesses(id),branch_id uuid not null references nb_branches(id),device_id uuid not null references nb_devices(id),opened_by uuid not null,opened_at timestamptz not null,opening_amount numeric(18,4) not null default 0,currency text not null,closed_by uuid,closed_at timestamptz,counted_amount numeric(18,4),status text not null check(status in('open','closed')));
create table nb_sales(id uuid primary key,business_id uuid not null references nb_businesses(id),branch_id uuid not null references nb_branches(id),device_id uuid not null references nb_devices(id),shift_id uuid references nb_cash_shifts(id),sale_number text,status text not null check(status in('completed','voided','refunded')),currency text not null,subtotal numeric(18,4) not null,discount_total numeric(18,4) not null default 0,total numeric(18,4) not null,customer_id uuid,occurred_at timestamptz not null);
create table nb_sale_lines(id uuid primary key,business_id uuid not null references nb_businesses(id),sale_id uuid not null references nb_sales(id),product_id uuid not null references nb_products(id),quantity numeric(18,4) not null check(quantity>0),unit_price numeric(18,4) not null,unit_cost numeric(18,4),discount numeric(18,4) not null default 0,line_total numeric(18,4) not null);
create table nb_payments(id uuid primary key,business_id uuid not null references nb_businesses(id),sale_id uuid not null references nb_sales(id),method text not null,currency text not null,amount numeric(18,4) not null check(amount>=0),reference text,occurred_at timestamptz not null);
create table nb_cash_movements(id uuid primary key,business_id uuid not null references nb_businesses(id),shift_id uuid not null references nb_cash_shifts(id),type text not null,amount numeric(18,4) not null,currency text not null,source_id uuid,reason text,actor_user_id uuid,occurred_at timestamptz not null);
create table nb_customers(id uuid primary key,business_id uuid not null references nb_businesses(id),name text not null,phone text,email text);
create table nb_orders(id uuid primary key,business_id uuid not null references nb_businesses(id),branch_id uuid references nb_branches(id),channel text not null check(channel in('web','pos','manual')),external_ref text,customer_id uuid references nb_customers(id),status text not null,fulfillment_type text check(fulfillment_type in('pickup','delivery')),currency text not null,total numeric(18,4) not null,created_at timestamptz not null default now(),unique(business_id,channel,external_ref));
create table nb_order_lines(id uuid primary key,business_id uuid not null references nb_businesses(id),order_id uuid not null references nb_orders(id),product_id uuid not null references nb_products(id),quantity numeric(18,4) not null,unit_price numeric(18,4) not null,line_total numeric(18,4) not null);
create table nb_sync_operations(id uuid primary key,business_id uuid not null references nb_businesses(id),device_id uuid not null references nb_devices(id),operation_type text not null,entity_type text not null,entity_id uuid not null,payload jsonb not null,occurred_at timestamptz not null,received_at timestamptz not null default now(),unique(device_id,id));
create table nb_sync_checkpoints(device_id uuid primary key references nb_devices(id),last_server_sequence bigint not null default 0,updated_at timestamptz not null default now());
create table nb_audit_log(id uuid primary key default gen_random_uuid(),business_id uuid not null references nb_businesses(id),actor_user_id uuid,device_id uuid,action text not null,entity_type text not null,entity_id uuid,before_data jsonb,after_data jsonb,occurred_at timestamptz not null default now());
-- RLS policies follow after tenant/auth claims ADR.
