"use client";
import { FormEvent, useMemo, useState } from "react";
import type { NexoSearchResponse, ProductSearchResult } from "../../../lib/product-search/types";
import { calculateOffer } from "../../../lib/product-search/validation";
const labels={exact:"Exacto",close:"Muy parecido",alternative:"Alternativa",unconfirmed:"Sin confirmar"};
export default function NexoBuscaClient(){
 const[preview,setPreview]=useState(""),[result,setResult]=useState<NexoSearchResponse|null>(null),[selected,setSelected]=useState<ProductSearchResult|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[quantity,setQuantity]=useState(1),[mode,setMode]=useState<"fixed"|"percent"|"final">("fixed"),[markup,setMarkup]=useState(5),[delivery,setDelivery]=useState(0),[audience,setAudience]=useState<"gestora"|"client">("gestora");
 const offer=useMemo(()=>selected?.price==null?null:calculateOffer({cost:selected.price,quantity,mode,markup,delivery}),[selected,quantity,mode,markup,delivery]);
 const ranked=useMemo(()=>result?[...result.results].sort((a,b)=>{const rank={exact:0,close:1,alternative:2,unconfirmed:3};const m=rank[a.match]-rank[b.match];if(m)return m;if(a.price==null)return 1;if(b.price==null)return-1;return a.price-b.price}):[],[result]);
 const sourceCount=useMemo(()=>new Set(ranked.map(x=>x.source).filter(Boolean)).size,[ranked]);
 const priced=ranked.filter(x=>x.price!=null);const low=priced.length?Math.min(...priced.map(x=>Number(x.price))):null;const high=priced.length?Math.max(...priced.map(x=>Number(x.price))):null;
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");setNotice("");setSelected(null);try{const r=await fetch("/api/gestoras/busca",{method:"POST",body:new FormData(e.currentTarget)}),b=await r.json();if(!r.ok)throw new Error(b.error);setResult(b)}catch(e){setError(e instanceof Error?e.message:"No pudimos buscar.")}finally{setBusy(false)}}
 const message=useMemo(()=>{if(!selected)return"";const price=offer?`${offer.productTotal.toFixed(2)} ${selected.currency}`:"precio por confirmar";return audience==="client"?`Hola. Encontré una opción que puede servirte:\n\n${selected.title}\nPrecio: ${price}${delivery?`\nMensajería: ${delivery.toFixed(0)} CUP`:""}\n\nSi te interesa, confirmo disponibilidad y detalles antes de reservar.`:`${selected.title}\nPrecio observado: ${selected.priceLabel||price}\nZona: ${selected.location||"no indicada"}\nFuente: ${selected.source||"web"}\n${selected.phone?`Contacto: ${selected.phone}\n`:""}${selected.url}\n\nConfirma disponibilidad, precio y modelo antes de ofrecer.${offer?`\nOferta: ${offer.productTotal.toFixed(2)} ${selected.currency} · Ganancia estimada: ${offer.earning.toFixed(2)} ${selected.currency}.`:""}`},[selected,offer,audience,delivery]);
 async function copyMessage(){if(!message)return;try{await navigator.clipboard.writeText(message);setNotice("Mensaje copiado.")}catch{setNotice("No se pudo copiar.")}}
 async function shareMessage(){if(!message)return;try{if(navigator.share){await navigator.share({title:selected?.title||"Opción encontrada",text:message});return}await copyMessage()}catch(e){if((e as Error)?.name!=="AbortError")setNotice("No se pudo compartir.")}}
 function resetSearch(){setResult(null);setSelected(null);setPreview("");setError("");setNotice("");setQuantity(1);setMarkup(5);setDelivery(0)}
 return <main className="impulsa-shell busca-shell">
  <header className="busca-topbar"><a className="busca-back" href="/impulsa" aria-label="Volver a Inicio">←</a><div><strong>Buscar producto</strong><small>Para un cliente</small></div><a className="busca-store" href="/impulsa/tienda">Mi tienda</a></header>
  {!result&&<><section className="busca-hero"><span>BÚSQUEDA</span><h1>Encuentra opciones para tu cliente</h1><p>Sube la foto y añade solo lo que importe para la compra.</p></section><section className="busca-grid solo"><form className="busca-card busca-form" onSubmit={submit}><label className="upload-zone">{preview?<img src={preview} alt="Vista previa"/>:<><b>📷 Añadir foto o captura</b><small>JPG, PNG o WebP</small></>}<input name="image" type="file" accept="image/jpeg,image/png,image/webp" required onChange={e=>{const f=e.target.files?.[0];if(f)setPreview(URL.createObjectURL(f))}}/></label><label>Qué necesita<textarea name="context" placeholder="Ej.: refrigerador similar, máximo 500 USD"/></label><label>Zona<input name="location" placeholder="Ej.: La Habana"/></label><button disabled={busy}>{busy?"Buscando opciones…":"Buscar"}</button>{busy&&<p role="status">Comparando ofertas públicas…</p>}{error&&<p className="busca-error" role="alert">{error}</p>}</form></section></>}
  {result&&<><section className="decision-head"><div><span>IDENTIFICADO</span><h1>{result.hypothesis.name}</h1><p>{Math.round(result.hypothesis.confidence*100)}% de confianza</p></div><button type="button" onClick={resetSearch}>Nueva búsqueda</button></section><section className="decision-strip"><div><small>OPCIONES</small><strong>{ranked.length}</strong></div><div><small>FUENTES</small><strong>{sourceCount||1}</strong></div><div><small>RANGO</small><strong>{low!=null&&high!=null?`${low}-${high}`:"Por confirmar"}</strong></div></section><details className="busca-details"><summary>Ver qué detectó la IA</summary><div><p>{result.hypothesis.request}</p><div className="spec-chips">{result.hypothesis.visibleAttributes.slice(0,6).map(x=><span key={x}>{x}</span>)}</div>{result.verificationQuestions.length>0&&<><h3>Antes de cerrar</h3><ul>{result.verificationQuestions.slice(0,5).map(x=><li key={x}>{x}</li>)}</ul></>}</div></details><section className="results compact-results"><header><span>MEJORES OPCIONES</span><h2>Compara y elige</h2><p>{result.summary}</p></header><div className="result-list">{ranked.map((item,index)=><article className={selected?.id===item.id?"result-card selected":"result-card"} key={item.id}><div className="result-meta"><span>{index===0?"Mejor coincidencia":labels[item.match]}</span>{item.source&&<small>{item.source}</small>}</div><h3>{item.title}</h3><strong className="result-price">{item.priceLabel||"Precio por confirmar"}</strong><div className="result-facts">{item.location&&<span>📍 {item.location}</span>}{item.observedAt&&<span>🕒 {item.observedAt}</span>}</div>{item.note&&<details className="result-note"><summary>Dato útil</summary><p>{item.note}</p></details>}<div className="result-actions"><button type="button" onClick={()=>setSelected(item)}>Preparar oferta</button>{item.url&&<a href={item.url} target="_blank" rel="noreferrer">Ver anuncio ↗</a>}</div></article>)}</div></section></>}
  {selected&&<section className="offer"><header><span>OFERTA</span><h2>Define tu precio</h2></header><div className="offer-grid"><div className="busca-card calculator"><label>Cantidad<input type="number" min="1" value={quantity} onChange={e=>setQuantity(Number(e.target.value)||1)}/></label><label>Ganancia<select value={mode} onChange={e=>setMode(e.target.value as any)}><option value="fixed">Sumar importe</option><option value="percent">Sumar porcentaje</option><option value="final">Precio final</option></select></label><label>{mode==="percent"?"Porcentaje":mode==="final"?"Precio final":"Ganancia por unidad"}<input type="number" min="0" step=".01" value={markup} onChange={e=>setMarkup(Number(e.target.value)||0)}/></label><label>Mensajería (CUP)<input type="number" min="0" value={delivery} onChange={e=>setDelivery(Number(e.target.value)||0)}/></label>{offer&&<div className="offer-total"><span>Cliente <b>{offer.productTotal.toFixed(2)} {selected.currency}</b></span><span>Tu ganancia <b>{offer.earning.toFixed(2)} {selected.currency}</b></span></div>}</div><div className="busca-card message"><div className="audience"><button type="button" className={audience==="gestora"?"active":""} onClick={()=>setAudience("gestora")}>Para mí</button><button type="button" className={audience==="client"?"active":""} onClick={()=>setAudience("client")}>Para cliente</button></div><textarea readOnly value={message}/><div className="message-actions"><button type="button" onClick={copyMessage}>Copiar</button><button type="button" onClick={shareMessage}>Compartir</button></div>{notice&&<p className="busca-notice" role="status">{notice}</p>}</div></div></section>}
 </main>
}
