"use client";
import { FormEvent, useMemo, useState } from "react";
import type { NexoSearchResponse, ProductSearchResult } from "../../../lib/product-search/types";
import { calculateOffer } from "../../../lib/product-search/validation";
const labels={exact:"Exacto",close:"Muy parecido",alternative:"Alternativa",unconfirmed:"Sin confirmar"};
export default function NexoBuscaClient(){
 const[preview,setPreview]=useState(""),[result,setResult]=useState<NexoSearchResponse|null>(null),[selected,setSelected]=useState<ProductSearchResult|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[quantity,setQuantity]=useState(1),[mode,setMode]=useState<"fixed"|"percent"|"final">("fixed"),[markup,setMarkup]=useState(5),[delivery,setDelivery]=useState(0),[audience,setAudience]=useState<"gestora"|"client">("gestora");
 const offer=useMemo(()=>selected?.price==null?null:calculateOffer({cost:selected.price,quantity,mode,markup,delivery}),[selected,quantity,mode,markup,delivery]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/gestoras/busca",{method:"POST",body:new FormData(e.currentTarget)}),b=await r.json();if(!r.ok)throw new Error(b.error);setResult(b)}catch(e){setError(e instanceof Error?e.message:"No pudimos buscar.")}finally{setBusy(false)}}
 const message=useMemo(()=>{if(!selected)return"";const price=offer?`${offer.productTotal.toFixed(2)} ${selected.currency}`:"precio por confirmar";return audience==="client"?`Hola. Estuve buscando ${result?.hypothesis.name||"el producto"} y encontré esta opción:\n\n• ${selected.title}\n• ${price}${delivery?`\n• Mensajería: ${delivery.toFixed(0)} CUP`:""}\n\nLa disponibilidad debe confirmarse antes de reservar. Si te interesa, avísame y verifico todos los detalles.`:`Esto fue lo que encontré para ${result?.hypothesis.name}:\n\n${selected.title}\nPrecio observado: ${selected.priceLabel||price}\nZona: ${selected.location||"no indicada"}\nContacto: ${selected.phone||"no publicado"}\nEnlace: ${selected.url}\nCoincidencia: ${labels[selected.match]}\n\nAntes de ofrecerlo, confirma disponibilidad, precio actual, modelo, ubicación y recogida. No compres ni reserves hasta que la cliente confirme.${offer?`\n\nOferta: ${offer.productTotal.toFixed(2)} ${selected.currency}. Ganancia estimada: ${offer.earning.toFixed(2)} ${selected.currency}. Mensajería separada: ${offer.delivery.toFixed(0)} CUP.`:""}`},[selected,result,offer,audience,delivery]);
 return <main className="impulsa-shell busca-shell">
  <header className="busca-topbar"><a className="busca-back" href="/impulsa" aria-label="Volver a Inicio">←</a><div><strong>Buscar producto</strong><small>Para un cliente</small></div><a className="busca-store" href="/impulsa/tienda">Mi tienda</a></header>
  <section className="busca-hero"><span>NUEVA BÚSQUEDA</span><h1>¿Qué está buscando tu cliente?</h1><p>Sube una foto o captura y añade cualquier detalle que te haya dado.</p><aside>🔒 Si es una captura, evita compartir datos personales que no hagan falta.</aside></section>
  <section className="busca-grid"><form className="busca-card busca-form" onSubmit={submit}><h2>Sube la solicitud</h2><label className="upload-zone">{preview?<img src={preview} alt="Vista previa"/>:<><b>📷 Añadir foto o captura</b><small>JPG, PNG o WebP · máximo 8 MB</small></>}<input name="image" type="file" accept="image/jpeg,image/png,image/webp" required onChange={e=>{const f=e.target.files?.[0];if(f)setPreview(URL.createObjectURL(f))}}/></label><label>¿Qué explicó el cliente?<textarea name="context" placeholder="Ej.: quiere una pesa como esta para su negocio"/></label><label>¿Dónde la necesita?<input name="location" placeholder="Municipio o reparto (opcional)"/></label><button disabled={busy}>{busy?"Buscando opciones…":"Buscar opciones"}</button>{busy&&<p role="status">Analizando la imagen y comparando opciones…</p>}{error&&<p className="busca-error" role="alert">{error}</p>}</form>
  {result&&<article className="busca-card understood"><span>IDENTIFICACIÓN</span><h2>{result.hypothesis.name}</h2><p>{result.hypothesis.request}</p><div className="confidence"><i style={{width:`${result.hypothesis.confidence*100}%`}}/></div><small>{Math.round(result.hypothesis.confidence*100)}% de confianza · revisa antes de ofrecer</small>{result.hypothesis.distinction&&<aside>{result.hypothesis.distinction}</aside>}<ul>{result.hypothesis.visibleAttributes.map(x=><li key={x}>✓ {x}</li>)}</ul>{result.hypothesis.missingImportant.length>0&&<div className="missing"><b>Conviene confirmar</b>{result.hypothesis.missingImportant.map(x=><span key={x}>{x}</span>)}</div>}</article>}</section>
  {result&&<section className="results"><header><span>OPCIONES ENCONTRADAS</span><h2>{result.results.length?`${result.results.length} opciones para comparar`:"Sin opciones verificables"}</h2><p>{result.summary}</p></header><div className="result-list">{result.results.map(item=><article className={selected?.id===item.id?"result-card selected":"result-card"} key={item.id}>{item.image&&<img src={item.image} alt=""/>}<div className="result-meta"><span>{labels[item.match]}</span>{item.source&&<small>{item.source}</small>}</div><h3>{item.title}</h3><b>{item.priceLabel||"Precio por confirmar"}</b>{item.location&&<p>{item.location}</p>}<button type="button" onClick={()=>setSelected(item)}>Preparar oferta</button>{item.url&&<a href={item.url} target="_blank" rel="noreferrer">Ver fuente ↗</a>}</article>)}</div></section>}
  {selected&&<section className="offer"><header><span>PREPARAR OFERTA</span><h2>Define tu precio y comparte.</h2></header><div className="offer-grid"><div className="busca-card calculator"><label>Cantidad<input type="number" min="1" value={quantity} onChange={e=>setQuantity(Number(e.target.value)||1)}/></label><label>Cómo quieres ganar<select value={mode} onChange={e=>setMode(e.target.value as any)}><option value="fixed">Sumar importe</option><option value="percent">Sumar porcentaje</option><option value="final">Definir precio final</option></select></label><label>{mode==="percent"?"Porcentaje":mode==="final"?"Precio final":"Ganancia por unidad"}<input type="number" min="0" step=".01" value={markup} onChange={e=>setMarkup(Number(e.target.value)||0)}/></label><label>Mensajería (CUP)<input type="number" min="0" value={delivery} onChange={e=>setDelivery(Number(e.target.value)||0)}/></label>{offer&&<div className="offer-total"><span>Precio al cliente <b>{offer.productTotal.toFixed(2)} {selected.currency}</b></span><span>Ganancia estimada <b>{offer.earning.toFixed(2)} {selected.currency}</b></span></div>}</div><div className="busca-card message"><div className="audience"><button type="button" className={audience==="gestora"?"active":""} onClick={()=>setAudience("gestora")}>Para mí</button><button type="button" className={audience==="client"?"active":""} onClick={()=>setAudience("client")}>Para el cliente</button></div><textarea readOnly value={message}/><button type="button" onClick={()=>navigator.clipboard.writeText(message)}>Copiar mensaje</button></div></div></section>}
 </main>
}