export type AreaResult={name:string;level:number|null;evidence:string;next:string};
export type StackItem={name:string;costMonthly:number|null;verdict:"se queda"|"se revisa"|"se cancela";evidence:string};
export type RiskItem={severity:"crítico"|"alto"|"medio";title:string;consequence:string;evidence:string};
export type RecoverableTask={task:string;hoursMonthly:number;hourlyCost:number|null;monthlyCost:number|null;formula:string};
export type BusinessAuditResult={scope:"inside";maturity:number|null;band:string;areas:AreaResult[];missing:number[];privacyBlocked:boolean;privacyReason?:string;hoursNote:string;crossNote:string;recoverableTasks:RecoverableTask[];recoverableHours:number|null;recoverableCost:number|null;stack:StackItem[];risks:RiskItem[]};

type AreaDef={name:string;questions:number[];next:string;levels:Array<{level:number;test:(text:string)=>boolean}>};
const has=(...terms:string[])=> (text:string)=>terms.some(term=>text.includes(term));
const areaDefs:AreaDef[]=[
 {name:"Captación y primer contacto",questions:[7,8,9,10,11],next:"Centralizar entradas, responder fuera de horario y registrar cuántas consultas se convierten.",levels:[{level:5,test:has("se convierten","conversión","conversion","panel","todo canal registrado")},{level:4,test:has("respuesta automática","respuesta automatica","sitio común","sitio comun","buzón común","buzon comun","se registran")},{level:3,test:has("número de empresa","numero de empresa","buzón de empresa","buzon de empresa","responsable de contestar")},{level:2,test:has("whatsapp","móvil personal","movil personal","contestador")}]},
 {name:"Agenda y citas",questions:[12,13,14,15,16],next:"Pasar a reserva online con recordatorios automáticos y medir no-shows.",levels:[{level:5,test:has("lista de espera","reprogramación automática","reprogramacion automatica","no-show medido","no show medido")},{level:4,test:has("reserva por internet","reserva online","recordatorios automáticos","recordatorios automaticos")},{level:3,test:has("programa de citas","software de citas","sistema de citas")},{level:2,test:has("excel","google calendar","calendario")}]},
 {name:"Cobro y facturación",questions:[17,18,19,20,21],next:"Conectar presupuesto, cobro y factura para reducir transcripción y seguimiento manual.",levels:[{level:5,test:has("cobro automático","cobro automatico","factura automática","factura automatica","avisos de impago","cobros recurrentes")},{level:4,test:has("presupuesto, cobro y factura conect","cobro y factura conect","impagos aparecen")},{level:3,test:has("programa de facturación","programa de facturacion","software de facturación","software de facturacion")},{level:2,test:has("plantilla","word","excel","whatsapp","email","correo")}]},
 {name:"Comunicación y seguimiento",questions:[15,22,23,25],next:"Automatizar recordatorios y petición de reseña manteniendo revisión humana del tono.",levels:[{level:5,test:has("secuencia","segmentad","se mide","miden aperturas","cuántos vuelven","cuantos vuelven")},{level:4,test:has("petición de reseña automática","peticion de reseña automatica","recordatorios automáticos","recordatorios automaticos")},{level:3,test:has("siempre","uno a uno","una a una")},{level:2,test:has("cuando nos acord","a mano","mensaje suelto")}]},
 {name:"Datos y medición",questions:[26,27,30],next:"Centralizar datos y revisar un conjunto pequeño de indicadores con periodicidad fija.",levels:[{level:5,test:has("panel","dashboard","alerta")},{level:4,test:has("revisamos cada mes","revisan cada mes","indicadores mensuales","datos en un sitio")},{level:3,test:has("crm","erp","programa central","sistema central")},{level:2,test:has("excel","móvil","movil","carpeta","whatsapp")}]},
 {name:"Retención y reactivación",questions:[22,24,25],next:"Crear avisos automáticos de recurrencia y reactivación, y medir cuántos vuelven.",levels:[{level:5,test:has("reactivación automática","reactivacion automatica","clientes dormidos","medimos cuántos vuelven","medimos cuantos vuelven")},{level:4,test:has("avisos automáticos","avisos automaticos","recordatorio automático","recordatorio automatico","renovación automática","renovacion automatica")},{level:3,test:has("avisamos a mano","se avisa a mano")},{level:2,test:has("deberían volver","deberian volver","tienen que volver","se supone que se acuerdan")}]},
 {name:"Seguridad, copias y RGPD",questions:[8,27,28,29],next:"Implantar copias automáticas verificadas, accesos individuales y responsable claro.",levels:[{level:5,test:has("restauración probada","restauracion probada","responsable identificado")},{level:4,test:has("copias automáticas verificadas","copias automaticas verificadas","accesos por persona","consentimientos")},{level:3,test:has("copia automática","copia automatica","accesos compartidos")},{level:2,test:has("pendrive","cuando nos acord","copia manual")}]},
 {name:"IA y automatización actual",questions:[33,34],next:"Empezar por una automatización pequeña, medible y con control de calidad.",levels:[{level:5,test:has("integrada en el proceso","control de calidad","ia integrada")},{level:4,test:has("varias automatizaciones","automatizaciones estables")},{level:3,test:has("respuesta automática","respuesta automatica","plantillas","automatización pequeña","automatizacion pequeña")},{level:2,test:has("probamos","se abandonó","se abandono","salió mal","salio mal","lo dejamos")}]},
];

export function parseAnswers(text:string){const out:Record<number,string>={};const re=/(?:^|\n)\s*(?:\*\*)?P(\d{1,2})(?:\.\*\*)?[^\n]*\n([\s\S]*?)(?=(?:\n\s*(?:\*\*)?P\d{1,2}(?:\.\*\*)?[^\n]*\n)|$)/gi;let m;while((m=re.exec(text)))out[Number(m[1])]=m[2].trim();return out}
function normalized(value:string){return value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"")}
function levelFor(def:AreaDef,answers:Record<number,string>){const values=def.questions.map(q=>answers[q]).filter(Boolean);if(!values.length)return null;const text=normalized(values.join(" "));for(const candidate of def.levels){if(candidate.test(text))return candidate.level}return 1}
function band(v:number|null){if(v===null)return"sin datos";if(v<2)return"artesanal";if(v<3)return"herramientas sueltas";if(v<4)return"digitalizado manual";if(v<4.5)return"conectado";return"automatizado"}
function evidenceFor(def:AreaDef,a:Record<number,string>){for(const q of def.questions){if(a[q]?.trim())return`P${q}: ${a[q].trim().slice(0,220)}`}return"Sin datos suficientes"}
function money(text:string){const values=[...text.matchAll(/(\d+(?:[.,]\d+)?)\s*(?:€|eur|euros?)\s*(?:\/\s*h|por\s+hora|la\s+hora)/gi)].map(m=>Number(m[1].replace(",","."))).filter(Number.isFinite);return values[0]??null}
function recoverableFrom(a:Record<number,string>):RecoverableTask[]{const source=[15,20,31].map(q=>a[q]).filter(Boolean).join("\n");if(!source)return[];const hourly=money(a[32]||"");const tasks:RecoverableTask[]=[];for(const raw of source.split(/\n+/)){const line=raw.replace(/^\s*\d+[.)-]?\s*/,"").trim();if(!line)continue;const text=normalized(line);let hours:number|null=null;let formula="";let m=text.match(/(\d+(?:[.,]\d+)?)\s*h(?:ora(?:s)?)?\s*(?:\/|al|a la|por)\s*dia/);if(!m&&/una hora\s*(?:al|a la|por)\s*dia/.test(text))m=["","1"] as RegExpMatchArray;if(m){const h=Number(m[1].replace(",","."));hours=Math.floor(h*5*4.3*10)/10;formula=`${h} h/día × 5 días × 4,3 = ${hours} h/mes`}
 if(hours===null){const w=text.match(/(\d+(?:[.,]\d+)?)\s*h(?:ora(?:s)?)?\s*(?:\/|a la|por)\s*semana/);if(w){const h=Number(w[1].replace(",","."));hours=Math.floor(h*4.3*10)/10;formula=`${h} h/semana × 4,3 = ${hours} h/mes`}}
 if(hours===null){const mo=text.match(/(\d+(?:[.,]\d+)?)\s*h(?:ora(?:s)?)?\s*(?:\/|al|por)\s*mes/);if(mo){hours=Number(mo[1].replace(",","."));formula=`${hours} h/mes`}}
 if(hours===null&&/(tarde entera|una tarde)/.test(text)){const explicit=text.match(/(\d+(?:[.,]\d+)?)\s*horas?/);if(explicit){hours=Number(explicit[1].replace(",","."));formula=`${hours} h/mes declaradas`}}
 if(hours!==null&&hours>0){const monthlyCost=hourly===null?null:Math.floor(hours*hourly);tasks.push({task:line.slice(0,180),hoursMonthly:hours,hourlyCost:hourly,monthlyCost,formula:monthlyCost===null?formula:`${formula} × ${hourly} €/h = ${monthlyCost} €/mes`})}}
 return tasks.slice(0,8)}
function stackFrom(a:Record<number,string>):StackItem[]{const text=a[26]||"";if(!text)return[];return text.split(/\n+/).map(x=>x.replace(/^[-*]\s*/,"").trim()).filter(Boolean).slice(0,12).map(line=>{const low=normalized(line);const costMatch=low.match(/(\d+(?:[.,]\d+)?)\s*(?:€|eur|euros?)\s*(?:al mes|\/mes|mes)/);const yearly=low.match(/(\d+(?:[.,]\d+)?)\s*(?:€|eur|euros?)\s*(?:al ano|\/ano|ano)/);const cost=costMatch?Number(costMatch[1].replace(",",".")):yearly?Math.round((Number(yearly[1].replace(",","."))/12)*100)/100:null;const unused=/(no lo usamos|no usamos|no lo llegamos a usar|se sigue pagando|ya no trabaja|abandon)/.test(low);return{name:line.slice(0,100),costMonthly:cost,verdict:unused?"se cancela":"se revisa",evidence:line}})}
function risksFrom(a:Record<number,string>):RiskItem[]{const combined=normalized([a[8],a[27],a[28],a[29]].filter(Boolean).join(" "));const out:RiskItem[]=[];if(/no hay copia|sin copia|papel/.test(combined))out.push({severity:"crítico",title:"Información sin copia verificable",consequence:"Una pérdida física o fallo puede dejar al negocio sin agenda o historial operativo.",evidence:evidenceFor({name:"",questions:[28],next:"",levels:[]},a)});if(/movil personal|móvil personal|mi movil|mi móvil/.test(combined))out.push({severity:"alto",title:"Datos operativos en un móvil personal",consequence:"El negocio depende de un dispositivo y una persona fuera de un control de acceso formal.",evidence:evidenceFor({name:"",questions:[27],next:"",levels:[]},a)});if(/ya no trabaja|se fue|sigue teniendo acceso|no cambiamos/.test(combined))out.push({severity:"crítico",title:"Accesos potencialmente abiertos a personal anterior",consequence:"Una cuenta crítica puede seguir accesible a alguien que ya no forma parte del negocio.",evidence:evidenceFor({name:"",questions:[29],next:"",levels:[]},a)});if(/solo yo|una sola persona|si no viene/.test(combined))out.push({severity:"alto",title:"Dependencia de una sola persona",consequence:"Una ausencia puede bloquear información o decisiones necesarias para operar.",evidence:evidenceFor({name:"",questions:[29],next:"",levels:[]},a)});return out}

export function runBusinessAudit(text:string):BusinessAuditResult{
 const lower=normalized(text);const blocked=["contrasena","password","api key","token de acceso","listado de clientes","historial clinico","exportacion de clientes"];
 const hit=blocked.find(x=>lower.includes(x));if(hit)return{scope:"inside",maturity:null,band:"bloqueado",areas:[],missing:[],privacyBlocked:true,privacyReason:`Se detectó contenido potencialmente sensible (${hit}). Retíralo antes de analizar.`,hoursNote:"No se procesaron las respuestas.",crossNote:"No se procesaron las respuestas.",recoverableTasks:[],recoverableHours:null,recoverableCost:null,stack:[],risks:[]};
 const a=parseAnswers(text);const missing=Array.from({length:36},(_,i)=>i+1).filter(n=>!a[n]?.trim());
 const areas=areaDefs.map(def=>{const level=levelFor(def,a);return{name:def.name,level,evidence:evidenceFor(def,a),next:def.next}});
 const scored=areas.map(x=>x.level).filter((x):x is number=>x!==null);const maturity=scored.length?Math.round((scored.reduce((x,y)=>x+y,0)/scored.length)*10)/10:null;
 const recoverableTasks=recoverableFrom(a);const recoverableHours=recoverableTasks.length?Math.floor(recoverableTasks.reduce((sum,x)=>sum+x.hoursMonthly,0)*10)/10:null;const costs=recoverableTasks.map(x=>x.monthlyCost).filter((x):x is number=>x!==null);const recoverableCost=costs.length===recoverableTasks.length&&costs.length?costs.reduce((sum,x)=>sum+x,0):null;
 const hoursNote=recoverableHours===null?"No hay tiempos con unidades suficientemente claras para calcular horas recuperables sin inventar.":recoverableCost===null?`${recoverableHours} h/mes recuperables según tiempos declarados. Falta un coste/hora inequívoco para valorar el ahorro.`:`${recoverableHours} h/mes · ${recoverableCost} €/mes, calculados solo con tiempos y coste/hora detectables en las respuestas.`;
 return{scope:"inside",maturity,band:band(maturity),areas,missing,privacyBlocked:false,hoursNote,crossNote:"Para ejecutar el Paso 9 del Kit 03 hacen falta también evidencias públicas: cada cruce debe tener una cita de fuera y otra del formulario.",recoverableTasks,recoverableHours,recoverableCost,stack:stackFrom(a),risks:risksFrom(a)};
}