import type { BusinessAuditResult } from "./business-audit";
import type { BusinessPublicResult } from "./business-public";

function esc(value: unknown) {
  return String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char] as string));
}
function list(items: string[]) { return items.length ? `<ul>${items.map((x) => `<li>${esc(x)}</li>`).join("")}</ul>` : `<p class="muted">Sin datos suficientes.</p>`; }

export function buildBusinessReportHtml(inside: BusinessAuditResult, outside: BusinessPublicResult | null) {
  const outsideScore = outside?.score ?? null;
  const crosses = outside?.crosses ?? [];
  const risks = inside.risks;
  const quickWins = outside?.quickWins ?? inside.areas.filter((a) => a.level !== null && a.level <= 2).slice(0, 5).map((a) => a.next);
  const actionRows = [
    ...(outside?.dimensions.filter((d) => d.status === "scored" && (d.score ?? 100) < 70).map((d) => ({ area: d.name, action: d.action, evidence: d.evidence.join(" · ") })) ?? []),
    ...inside.areas.filter((a) => a.level !== null && a.level <= 3).map((a) => ({ area: a.name, action: a.next, evidence: a.evidence })),
  ].slice(0, 12);
  const style = `
    :root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#111;background:#f5f6f7}*{box-sizing:border-box}body{margin:0}.wrap{max-width:1080px;margin:auto;padding:36px 20px 80px}.hero{background:#0d1117;color:#fff;border-radius:28px;padding:34px}.eyebrow{font-size:12px;letter-spacing:.16em;text-transform:uppercase;opacity:.65}.hero h1{font-size:clamp(32px,6vw,64px);line-height:.96;margin:12px 0 20px}.scoregrid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:28px}.score{background:#fff;color:#111;border-radius:18px;padding:18px}.score b{font-size:34px}.score small{display:block;color:#68707a;margin-top:6px}.section{background:#fff;border:1px solid #e5e7eb;border-radius:22px;padding:26px;margin-top:18px}.section h2{margin-top:0;font-size:25px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.card{border:1px solid #e5e7eb;border-radius:16px;padding:16px}.card h3{margin:0 0 8px}.badge{display:inline-block;border:1px solid #d6dae0;border-radius:999px;padding:4px 9px;font-size:12px}.danger{border-color:#f1b8b8;background:#fff8f8}.warn{border-color:#efd9a3;background:#fffcf3}.muted{color:#6b7280}.meter{height:8px;border-radius:999px;background:#eceff2;overflow:hidden;margin:10px 0}.meter span{display:block;height:100%;background:#111}.journey{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:8px}.step{background:#f6f7f8;border-radius:14px;padding:14px;font-size:13px}.table{width:100%;border-collapse:collapse}.table th,.table td{text-align:left;vertical-align:top;border-top:1px solid #e5e7eb;padding:12px 8px}.table th{font-size:12px;text-transform:uppercase;letter-spacing:.08em;color:#68707a}ul{padding-left:20px}li{margin:5px 0}@media(max-width:720px){.scoregrid,.grid{grid-template-columns:1fr 1fr}.hero{padding:26px 20px}}@media(max-width:480px){.scoregrid,.grid{grid-template-columns:1fr}}@media print{body{background:#fff}.wrap{max-width:none;padding:0}.hero,.section{break-inside:avoid;border-radius:0}.section{border-left:0;border-right:0}.no-print{display:none}}
  `;
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NEXO Business Audit</title><style>${style}</style></head><body><main class="wrap">
  <section class="hero"><div class="eyebrow">NEXO · BUSINESS AUDIT</div><h1>Una sola lectura del negocio: fuera + dentro.</h1><p>Informe basado únicamente en evidencia pública observable y respuestas declaradas. Las dos notas se mantienen separadas por metodología.</p><div class="scoregrid">
    <div class="score"><span>Presencia digital</span><b>${outsideScore === null ? "—" : esc(outsideScore)}</b><small>${outside ? esc(outside.band) : "sin URL pública"}</small></div>
    <div class="score"><span>Madurez interna</span><b>${inside.maturity === null ? "—" : esc(inside.maturity.toFixed(1))}</b><small>/ 5 · ${esc(inside.band)}</small></div>
    <div class="score"><span>Tiempo recuperable</span><b>${inside.recoverableHours === null ? "—" : esc(inside.recoverableHours)}</b><small>h/mes</small></div>
    <div class="score"><span>Riesgos críticos/altos</span><b>${risks.filter((r) => r.severity !== "medio").length}</b><small>detectados</small></div>
  </div></section>
  <section class="section"><h2>Resumen ejecutivo</h2><p>${esc(inside.hoursNote)}</p><p>${outside ? `La presencia digital queda en ${esc(outsideScore)} /100 (${esc(outside.band)}), calculada solo sobre dimensiones con al menos dos evidencias. ` : "No se proporcionó URL pública; la mitad exterior no se puntúa. "}La madurez interna es ${inside.maturity === null ? "sin datos" : `${esc(inside.maturity.toFixed(1))}/5 (${esc(inside.band)})`}.</p>${crosses.length ? `<p>Se detectaron <b>${crosses.length}</b> inconsistencias exterior/interior con evidencia de ambos lados.</p>` : `<p class="muted">No hay cruces demostrables con la evidencia actual.</p>`}</section>
  <section class="section"><h2>Qué no encaja</h2><div class="grid">${crosses.length ? crosses.map((x) => `<article class="card ${x.severity === "critical" ? "danger" : "warn"}"><span class="badge">${esc(x.severity)}</span><h3>${esc(x.title)}</h3><p><b>Fuera:</b> ${esc(x.outsideEvidence)}</p><p><b>Dentro:</b> ${esc(x.insideEvidence)}</p><p>${esc(x.implication)}</p></article>`).join("") : `<p class="muted">Sin cruces suficientes.</p>`}</div></section>
  ${outside ? `<section class="section"><h2>Mapa actual del cliente</h2><div class="journey">${outside.currentJourney.map((x, i) => `<div class="step"><b>${i + 1}</b><br>${esc(x)}</div>`).join("")}</div></section>` : ""}
  ${outside ? `<section class="section"><h2>Parte A · Exterior</h2><div class="grid">${outside.dimensions.map((d) => `<article class="card"><span class="badge">${esc(d.name)} · peso ${d.weight}</span><h3>${d.score === null ? "Sin datos" : `${d.score}/100`}</h3>${d.score !== null ? `<div class="meter"><span style="width:${Math.max(0, Math.min(100, d.score))}%"></span></div>` : ""}${list(d.evidence)}<p><b>Acción:</b> ${esc(d.action)}</p></article>`).join("")}</div></section>` : ""}
  <section class="section"><h2>Parte B · Interior</h2><div class="grid">${inside.areas.map((a) => `<article class="card"><span class="badge">Nivel ${a.level ?? "—"} /5</span><h3>${esc(a.name)}</h3><p><b>Evidencia:</b> ${esc(a.evidence)}</p><p><b>Siguiente nivel:</b> ${esc(a.next)}</p></article>`).join("")}</div></section>
  ${outside ? `<section class="section"><h2>Mapa futuro</h2><div class="journey">${outside.futureJourney.map((x, i) => `<div class="step"><b>${i + 1}</b><br>${esc(x)}</div>`).join("")}</div></section>` : ""}
  <section class="section"><h2>Plan único de acción</h2><table class="table"><thead><tr><th>Área</th><th>Acción</th><th>Evidencia</th></tr></thead><tbody>${actionRows.map((r) => `<tr><td>${esc(r.area)}</td><td>${esc(r.action)}</td><td>${esc(r.evidence)}</td></tr>`).join("")}</tbody></table></section>
  <section class="section"><h2>Quick wins</h2>${list(quickWins)}</section>
  ${outside ? `<section class="section"><h2>Roadmap</h2><div class="grid">${outside.roadmap.map((r) => `<article class="card"><h3>${esc(r.horizon)}</h3>${list(r.actions)}</article>`).join("")}</div></section>` : ""}
  <section class="section"><h2>Qué no automatizar todavía</h2>${outside ? list(outside.doNotAutomateYet) : list(inside.areas.filter((a) => a.level === 1).map((a) => `${a.name}: estabilizar y documentar primero.`))}</section>
  <section class="section"><h2>Riesgos operativos</h2><div class="grid">${risks.length ? risks.map((r) => `<article class="card ${r.severity === "crítico" ? "danger" : "warn"}"><span class="badge">${esc(r.severity)}</span><h3>${esc(r.title)}</h3><p>${esc(r.consequence)}</p><p><b>Evidencia:</b> ${esc(r.evidence)}</p></article>`).join("") : `<p class="muted">No se detectaron riesgos con las reglas actuales.</p>`}</div></section>
  <section class="section"><h2>Metodología y límites</h2><p>Presencia digital /100 y madurez interna /5 son medidas independientes y nunca se promedian entre sí. Las dimensiones públicas sin dos evidencias quedan como “sin datos”; su peso se redistribuye proporcionalmente entre las dimensiones puntuables. “No aplica” tampoco equivale a cero.</p>${outside ? list(outside.limitations) : ""}<p class="muted">NEXO no accede a sistemas privados del negocio para esta auditoría.</p></section>
  </main></body></html>`;
}
